/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ClasesPlanas;

import ConexionBD.Conexion;
import static ConexionBD.Conexion.con;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Paola Barrera Tenorio 2192007348 
 */

public class Nota extends javax.swing.JPanel implements Printable {

    /**
     * Creates new form Nota
     */
    public Nota() {
        initComponents();
        
        Fecha();
        TxtFields();
        llenarComboBoxCliente(cmbCliente, (Connection) con);
        llenarComboBoxCajera(cmbCajera, (Connection) con);
        try {
        lblNumeroNota.setText(generarSiguienteNumero(con));
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al generar número: " + ex.getMessage());
        ex.printStackTrace();
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNotaRemision = new javax.swing.JLabel();
        lblFechaDia = new javax.swing.JLabel();
        lblNumeroNR = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPanBlanco = new javax.swing.JLabel();
        txtTeleras = new javax.swing.JTextField();
        lblCantidadPB = new javax.swing.JLabel();
        lblTipoPB = new javax.swing.JLabel();
        lblPrecioPB = new javax.swing.JLabel();
        lblSubtotalPB = new javax.swing.JLabel();
        txtBolilloLiso = new javax.swing.JTextField();
        txtBolilloAjonjoli = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPanDulce = new javax.swing.JLabel();
        lblCantidadPD = new javax.swing.JLabel();
        txtBizcocho = new javax.swing.JTextField();
        lblTipoPD = new javax.swing.JLabel();
        lblPrecioPD = new javax.swing.JLabel();
        lblSubtotalPD = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblCajas = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCantidadCajas = new javax.swing.JTextField();
        lblTipoCajas = new javax.swing.JLabel();
        lblPrecioCajas = new javax.swing.JLabel();
        lblSubtotalCajas = new javax.swing.JLabel();
        lblImporteTotal = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTelera = new javax.swing.JLabel();
        lblBolilloLiso = new javax.swing.JLabel();
        lblBolilloAjonjoli = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFeite = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblBizcocho = new javax.swing.JLabel();
        lblFeite = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblCantidadCajas = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblNumeroNota = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbCajera = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 214, 155));

        jPanel2.setBackground(new java.awt.Color(165, 105, 66));

        lblNotaRemision.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        lblNotaRemision.setForeground(new java.awt.Color(255, 255, 255));
        lblNotaRemision.setText("- Nota de remision -");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNotaRemision)
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotaRemision)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblFechaDia.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblFechaDia.setText("Fecha:");

        lblNumeroNR.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblNumeroNR.setText("Nota de remisión #");

        lblCliente.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblCliente.setText("Cliente Reparto");

        cmbCliente.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDireccion.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblDireccion.setText("General Emiliano Zapata 141, Cuartos Constitución 53690, Naucalpan de Juárez");

        lblTelefono.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblTelefono.setText("Teléfono");

        jSeparator1.setBackground(new java.awt.Color(165, 105, 66));
        jSeparator1.setForeground(new java.awt.Color(165, 105, 66));

        lblPanBlanco.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPanBlanco.setText("- PAN BLANCO -");

        txtTeleras.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtTeleras.setText("0");

        lblCantidadPB.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblCantidadPB.setText("Cantidad");

        lblTipoPB.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblTipoPB.setText("Tipo");

        lblPrecioPB.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPrecioPB.setText("Precio");

        lblSubtotalPB.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblSubtotalPB.setText("Subtotal");

        txtBolilloLiso.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtBolilloLiso.setText("0");

        txtBolilloAjonjoli.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtBolilloAjonjoli.setText("0");

        jSeparator2.setBackground(new java.awt.Color(165, 105, 66));
        jSeparator2.setForeground(new java.awt.Color(165, 105, 66));

        lblPanDulce.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPanDulce.setText("- PAN DULCE -");

        lblCantidadPD.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblCantidadPD.setText("Cantidad");

        txtBizcocho.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtBizcocho.setText("0");

        lblTipoPD.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblTipoPD.setText("Tipo");

        lblPrecioPD.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPrecioPD.setText("Precio");

        lblSubtotalPD.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblSubtotalPD.setText("Subtotal");

        jSeparator3.setBackground(new java.awt.Color(165, 105, 66));
        jSeparator3.setForeground(new java.awt.Color(165, 105, 66));

        lblCajas.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblCajas.setText("- CAJAS -");

        lblCantidad.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblCantidad.setText("Cantidad");

        txtCantidadCajas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtCantidadCajas.setText("0");

        lblTipoCajas.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblTipoCajas.setText("Tipo");

        lblPrecioCajas.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPrecioCajas.setText("Precio");

        lblSubtotalCajas.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblSubtotalCajas.setText("Subtotal");

        lblImporteTotal.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblImporteTotal.setText("IMPORTE TOTAL");

        lblFecha.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblFecha.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel2.setText("Teleras");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel3.setText("Bolillos Lisos");

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel4.setText("Bolillos Ajonjolí");

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel5.setText("2.00");

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel6.setText("2.00");

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel7.setText("2.50");

        lblTelera.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblTelera.setText("0.0");

        lblBolilloLiso.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblBolilloLiso.setText("0.0");

        lblBolilloAjonjoli.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblBolilloAjonjoli.setText("0.0");

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel11.setText("Bizcocho ");

        txtFeite.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtFeite.setText("0");

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel12.setText("Feite");

        jLabel13.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel13.setText("10.00");

        jLabel14.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel14.setText("11.00");

        lblBizcocho.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblBizcocho.setText("0.0");

        lblFeite.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblFeite.setText("0.0");

        jLabel17.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel17.setText("Cartón");

        jLabel18.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel18.setText("10.00");

        lblCantidadCajas.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblCantidadCajas.setText("0.0");

        lblTotal.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblTotal.setText("0.0");

        lblNumeroNota.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblNumeroNota.setText("jLabel22");

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel1.setText("55 53 07 58 55");

        btnCalcular.setBackground(new java.awt.Color(165, 105, 66));
        btnCalcular.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel8.setText("Cajera");

        cmbCajera.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        cmbCajera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel9.setText("Cliente");

        jTextField1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblCantidadPD)
                .addGap(87, 87, 87)
                .addComponent(lblTipoPD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrecioPD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(lblSubtotalPD)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBolilloLiso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTeleras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBolilloAjonjoli, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(101, 101, 101)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblBolilloLiso)
                                        .addComponent(lblTelera))
                                    .addComponent(lblBolilloAjonjoli)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(lblPanBlanco))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(lblPanDulce))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(lblCajas))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(txtCantidadCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel18)
                                .addGap(94, 94, 94)
                                .addComponent(lblCantidadCajas)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblCantidadPB)
                .addGap(86, 86, 86)
                .addComponent(lblTipoPB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrecioPB)
                .addGap(92, 92, 92)
                .addComponent(lblSubtotalPB)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblCantidad)
                .addGap(99, 99, 99)
                .addComponent(lblTipoCajas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrecioCajas)
                .addGap(102, 102, 102)
                .addComponent(lblSubtotalCajas)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFechaDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImporteTotal)
                .addGap(31, 31, 31)
                .addComponent(lblTotal)
                .addGap(144, 144, 144))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNumeroNR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumeroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblTelefono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(145, 145, 145)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbCajera, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFeite)
                            .addComponent(txtBizcocho, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBizcocho)
                            .addComponent(lblFeite)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDia)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroNR)
                    .addComponent(lblNumeroNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(cmbCajera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblPanBlanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadPB)
                    .addComponent(lblTipoPB)
                    .addComponent(lblPrecioPB)
                    .addComponent(lblSubtotalPB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeleras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(lblTelera))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBolilloLiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(lblBolilloLiso))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBolilloAjonjoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(lblBolilloAjonjoli))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblPanDulce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadPD)
                    .addComponent(lblTipoPD)
                    .addComponent(lblPrecioPD)
                    .addComponent(lblSubtotalPD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBizcocho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(lblBizcocho))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFeite, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(lblFeite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCajas)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(lblTipoCajas)
                    .addComponent(lblPrecioCajas)
                    .addComponent(lblSubtotalCajas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(lblCantidadCajas))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporteTotal)
                    .addComponent(lblTotal))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

//Botón Calcular
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        subtotales();
        ImporteTotal();
    }//GEN-LAST:event_btnCalcularActionPerformed

//------------------------------------------------------------------------------
    //Método para generar la fecha 
//------------------------------------------------------------------------------
    private void Fecha(){

    LocalDate hoy = LocalDate.now();
    DateTimeFormatter formatoDia = DateTimeFormatter.ofPattern("EEEE", new Locale("es", "ES"));
    lblFechaDia.setText("Fecha: " + hoy.format(formatoDia));
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaActual = sdf.format(new Date());
    lblFecha.setText( fechaActual);
}    
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para limitar a escribir solo números en los Textfield
//------------------------------------------------------------------------------
    private void limitarNumeros(JTextField textField) {
        textField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) { // Solo permite números
                    e.consume(); // Bloquea la entrada si no es un número
                }
            }
        });
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para txtFields
//------------------------------------------------------------------------------
    private void TxtFields(){
    
    limitarNumeros(txtTeleras);
    limitarNumeros(txtBolilloLiso);
    limitarNumeros(txtBolilloAjonjoli);
    limitarNumeros(txtBizcocho);
    limitarNumeros(txtFeite);
    limitarNumeros(txtCantidadCajas);
    
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para llenar el comboBox de los clientes
//------------------------------------------------------------------------------
   public void llenarComboBoxCliente(JComboBox<String> comboBox, Connection conn) {
    String sql = "SELECT idClienteReparto, CR_Nombre, CR_Telefono FROM clientereparto"; 
    Connection con = Conexion.conectar();

    try (PreparedStatement stmt = con.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        comboBox.removeAllItems(); // Limpiar el JComboBox antes de llenarlo
        comboBox.addItem("Seleccione cliente");
        
        while (rs.next()) {
            int idCliente = rs.getInt("idClienteReparto");
            String nombre = rs.getString("CR_Nombre");
            String telefono = rs.getString("CR_Telefono");
            
            String item = idCliente + " - " + nombre + ", " + telefono;  // Ej: "3 - Ana Torres, 5551234567"
            comboBox.addItem(item);
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos en el ComboBox.");
    }
}
//------------------------------------------------------------------------------    

    
//------------------------------------------------------------------------------
    //Método para llenar el comboBox de las cajeras
//------------------------------------------------------------------------------
    
    public void llenarComboBoxCajera(JComboBox<String> comboBox, Connection conn) {
    String sql = "SELECT idUsuario, U_nombre FROM usuario WHERE U_Rol = 'cajera'"; 
    java.sql.Connection con = Conexion.conectar();
     
    try (PreparedStatement stmt = con.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        comboBox.removeAllItems(); // Limpiar el JComboBox antes de llenarlo
        
        
        while (rs.next()) {
            int idUsuario = rs.getInt("idUsuario");
            String nombre = rs.getString("U_nombre");
            comboBox.addItem(idUsuario + " - " + nombre); // Ej: "3 - Ana Torres"
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos en el ComboBox.");
    }
    }
//------------------------------------------------------------------------------    
    
//------------------------------------------------------------------------------
    //Método para calcular los subtotales
//------------------------------------------------------------------------------
private void subtotales(){

    try {
        // Verificamos que todos los campos tengan contenido
        if (!txtTeleras.getText().isEmpty() &&
            !txtBolilloLiso.getText().isEmpty() &&
            !txtBolilloAjonjoli.getText().isEmpty() &&
            !txtBizcocho.getText().isEmpty() &&
            !txtFeite.getText().isEmpty() &&
            !txtCantidadCajas.getText().isEmpty()) {

            float subtotalTelera = Float.parseFloat(txtTeleras.getText()) * 2.00f;
            float subtotalBolillo = Float.parseFloat(txtBolilloLiso.getText()) * 2.00f;
            float subtotalAjonjoli = Float.parseFloat(txtBolilloAjonjoli.getText()) * 2.50f;
            float subtotalBizcocho = Float.parseFloat(txtBizcocho.getText()) * 10.00f;
            float subtotalFeite = Float.parseFloat(txtFeite.getText()) * 11.00f;
            float subtotalCajas = Float.parseFloat(txtCantidadCajas.getText()) * 10.00f;

            // Mostrar los resultados
            lblTelera.setText(String.format("%.2f", subtotalTelera));
            lblBolilloLiso.setText(String.format("%.2f", subtotalBolillo));
            lblBolilloAjonjoli.setText(String.format("%.2f", subtotalAjonjoli));
            lblBizcocho.setText(String.format("%.2f", subtotalBizcocho));
            lblFeite.setText(String.format("%.2f", subtotalFeite));
            lblCantidadCajas.setText(String.format("%.2f", subtotalCajas));
        } else {
            // Si algún campo está vacío, mostramos 0
            lblTelera.setText("0.00");
            lblBolilloLiso.setText("0.00");
            lblBolilloAjonjoli.setText("0.00");
            lblBizcocho.setText("0.00");
            lblFeite.setText("0.00");
            lblCantidadCajas.setText("0.00");
        }
    } catch (NumberFormatException e) {
        
        lblTelera.setText("0.00");
        lblBolilloLiso.setText("0.00");
        lblBolilloAjonjoli.setText("0.00");
        lblBizcocho.setText("0.00");
        lblFeite.setText("0.00");
        lblCantidadCajas.setText("0.00");
    }
}
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para calcular el importe total
//------------------------------------------------------------------------------
    private void ImporteTotal(){
    
    float total = 0;
    total = Float.parseFloat(lblTelera.getText()) + Float.parseFloat(lblBolilloLiso.getText()) + Float.parseFloat(lblBolilloAjonjoli.getText()) +
            Float.parseFloat(lblBizcocho.getText()) + Float.parseFloat(lblFeite.getText()) + Float.parseFloat(lblCantidadCajas.getText());
    
    lblTotal.setText(String.format("%.2f", total));
    
    }
//------------------------------------------------------------------------------
    
    
   
//------------------------------------------------------------------------------
    //Método para generar el número de la nota de remisión
//------------------------------------------------------------------------------
    
    // Obtener el último número de remisión generado
    private String obtenerUltimoNumero() throws SQLException {
        String sql = "SELECT LP_NumNotaRemision FROM listapedido ORDER BY idListaPedido DESC LIMIT 1";
        try (PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getString("LP_NumNotaRemision");
            } else {
                return "000000"; // Si no hay registros todavía
            }
        }
    }

    // Generar el siguiente número
    private String generarSiguienteNumero(Connection con1) throws SQLException {
    String ultimo = obtenerUltimoNumero();
    int numero = Integer.parseInt(ultimo);
    numero++;
    return String.format("%06d", numero);
    }

    // Insertar la nueva nota
    private void insertarNuevaNota() throws SQLException {
        String nuevoNumero = generarSiguienteNumero(con);
        String sql = "INSERT INTO listapedido (LP_NumNotaRemision) VALUES (?)";
        try (PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, nuevoNumero);
            ps.executeUpdate();
        }
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para agregar los datos de los TxtFields a la tabla ReportesVenta
//------------------------------------------------------------------------------
    public void Agregar() {
    Date fecha = parseDate(lblFecha.getText()); 
    if (fecha == null) {
        JOptionPane.showMessageDialog(null, "Fecha inválida. Ingrese en formato yyyy-MM-dd.");
        return;
    }

    String seleccionadoCliente = cmbCliente.getSelectedItem().toString();
    if (seleccionadoCliente.equals("Seleccione cliente")) {
        JOptionPane.showMessageDialog(null, " No se guardará el pedido.");
        return; // Aquí detenemos el guardado pero sin marcar error
    }

    java.sql.Date fechaSQL = new java.sql.Date(fecha.getTime());

    int totalPB = Integer.parseInt(txtTeleras.getText().trim()) +
                  Integer.parseInt(txtBolilloLiso.getText().trim()) +
                  Integer.parseInt(txtBolilloAjonjoli.getText().trim());

    int totalPD = Integer.parseInt(txtBizcocho.getText().trim()) +
                  Integer.parseInt(txtFeite.getText().trim());

    float importeTotal = Float.parseFloat(lblTotal.getText().trim());

    String seleccionadoCajera = cmbCajera.getSelectedItem().toString();
    int idUsuarioCajera = Integer.parseInt(seleccionadoCajera.split(" - ")[0]);
    int idUsuarioCliente = Integer.parseInt(seleccionadoCliente.split(" - ")[0]);

    try {
        Connection con = Conexion.conectar();

        String numeroNota = generarSiguienteNumero(con);

        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO listapedido (LP_Fecha, LP_NumNotaRemision, LP_TotalPanBlanco, LP_TotalPanDulce, LP_ImporteTotal, LP_IDClienteReparto, LP_IDUsuario) VALUES (?, ?, ?, ?, ?, ?, ?)"
        );

        ps.setDate(1, fechaSQL);
        ps.setString(2, numeroNota);
        ps.setInt(3, totalPB);
        ps.setInt(4, totalPD);
        ps.setFloat(5, importeTotal);
        ps.setInt(6, idUsuarioCliente);
        ps.setInt(7, idUsuarioCajera);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registro guardado correctamente.");
        con.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage());
    }

}
//------------------------------------------------------------------------------
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbCajera;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBizcocho;
    private javax.swing.JLabel lblBolilloAjonjoli;
    private javax.swing.JLabel lblBolilloLiso;
    private javax.swing.JLabel lblCajas;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidadCajas;
    private javax.swing.JLabel lblCantidadPB;
    private javax.swing.JLabel lblCantidadPD;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaDia;
    private javax.swing.JLabel lblFeite;
    private javax.swing.JLabel lblImporteTotal;
    private javax.swing.JLabel lblNotaRemision;
    private javax.swing.JLabel lblNumeroNR;
    private javax.swing.JLabel lblNumeroNota;
    private javax.swing.JLabel lblPanBlanco;
    private javax.swing.JLabel lblPanDulce;
    private javax.swing.JLabel lblPrecioCajas;
    private javax.swing.JLabel lblPrecioPB;
    private javax.swing.JLabel lblPrecioPD;
    private javax.swing.JLabel lblSubtotalCajas;
    private javax.swing.JLabel lblSubtotalPB;
    private javax.swing.JLabel lblSubtotalPD;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelera;
    private javax.swing.JLabel lblTipoCajas;
    private javax.swing.JLabel lblTipoPB;
    private javax.swing.JLabel lblTipoPD;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtBizcocho;
    private javax.swing.JTextField txtBolilloAjonjoli;
    private javax.swing.JTextField txtBolilloLiso;
    private javax.swing.JTextField txtCantidadCajas;
    private javax.swing.JTextField txtFeite;
    private javax.swing.JTextField txtTeleras;
    // End of variables declaration//GEN-END:variables

//------------------------------------------------------------------------------
    //Método para imprimir
//------------------------------------------------------------------------------
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        
    if(pageIndex == 0){
    Graphics2D graphics2d=(Graphics2D) graphics;
    graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
    printAll(graphics2d);
    return PAGE_EXISTS;
    }
    else{
    return NO_SUCH_PAGE;
    }
    
    
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método ParseInt
//------------------------------------------------------------------------------

    private int ParseInt(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Date parseDate(String fecha) {
         try {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd"); 
        java.util.Date fechaUtil = formato.parse(fecha);
        return new java.sql.Date(fechaUtil.getTime());
    } 
         catch (ParseException e) {
        System.out.println("Error al convertir la fecha: " + e.getMessage());
        return null; // Devuelve null si hay error
    }
    }
//------------------------------------------------------------------------------
    
}
