/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ClasesPlanas;

import ConexionBD.Conexion;
import java.sql.Connection;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Paola Barrera Tenorio 2192007348
 */
public class Pedido extends javax.swing.JPanel implements Printable {

    
    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
        Fecha();
        java.sql.Connection con =  Conexion.conectar();
        llenarComboBox(cmbCliente, (Connection) con);
        TxtFields();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblListaPedido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblPanBlanco = new javax.swing.JLabel();
        lblTeleras = new javax.swing.JLabel();
        txtTeleras = new javax.swing.JTextField();
        lblBolilloLiso = new javax.swing.JLabel();
        txtBolilloLiso = new javax.swing.JTextField();
        lblBolilloAjonjoli = new javax.swing.JLabel();
        txtBolilloAjonjoli = new javax.swing.JTextField();
        lblTotalPanBlanco = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblConchaBlanca = new javax.swing.JLabel();
        lblConchaChoco = new javax.swing.JLabel();
        lblConchaAmarilla = new javax.swing.JLabel();
        lblCuernito = new javax.swing.JLabel();
        lblHojaldra = new javax.swing.JLabel();
        lblBisquet = new javax.swing.JLabel();
        lblColchon = new javax.swing.JLabel();
        lblMantecada = new javax.swing.JLabel();
        lblBigote = new javax.swing.JLabel();
        lblMoño = new javax.swing.JLabel();
        lblNovia = new javax.swing.JLabel();
        lblCocol = new javax.swing.JLabel();
        lblMordida = new javax.swing.JLabel();
        lblPiojosa = new javax.swing.JLabel();
        lblCema = new javax.swing.JLabel();
        txtConchaBlanca = new javax.swing.JTextField();
        txtConchaChoco = new javax.swing.JTextField();
        txtConchaAmarilla = new javax.swing.JTextField();
        txtCuernito = new javax.swing.JTextField();
        txtHojaldra = new javax.swing.JTextField();
        txtBisquet = new javax.swing.JTextField();
        txtColchon = new javax.swing.JTextField();
        txtMantecada = new javax.swing.JTextField();
        txtBigote = new javax.swing.JTextField();
        txtMoño = new javax.swing.JTextField();
        txtNovia = new javax.swing.JTextField();
        txtCocol = new javax.swing.JTextField();
        txtMordida = new javax.swing.JTextField();
        txtPiojosa = new javax.swing.JTextField();
        txtCema = new javax.swing.JTextField();
        lblMaria = new javax.swing.JLabel();
        lblBeso = new javax.swing.JLabel();
        lblAlmeja = new javax.swing.JLabel();
        lblCacahuate = new javax.swing.JLabel();
        lblHueso = new javax.swing.JLabel();
        lblRosca = new javax.swing.JLabel();
        lblEmpanadaBiz = new javax.swing.JLabel();
        lblPiedra = new javax.swing.JLabel();
        lblLadrillo = new javax.swing.JLabel();
        lblGalletaE = new javax.swing.JLabel();
        lblGalletaNuez = new javax.swing.JLabel();
        lblGalletaCho = new javax.swing.JLabel();
        lblGendarme = new javax.swing.JLabel();
        txtPolvoron = new javax.swing.JTextField();
        txtPolvoronMazapan = new javax.swing.JTextField();
        txtMaria = new javax.swing.JTextField();
        txtBeso = new javax.swing.JTextField();
        txtAlmeja = new javax.swing.JTextField();
        txtCacahuate = new javax.swing.JTextField();
        txtHueso = new javax.swing.JTextField();
        txtRosca = new javax.swing.JTextField();
        txtEmpanadaBiz = new javax.swing.JTextField();
        txtPiedra = new javax.swing.JTextField();
        txtLadrillo = new javax.swing.JTextField();
        txtGalletaE = new javax.swing.JTextField();
        txtGalletaCho = new javax.swing.JTextField();
        txtGalletaNuez = new javax.swing.JTextField();
        txtGendarme = new javax.swing.JTextField();
        lblDonaMoka = new javax.swing.JLabel();
        lblDonaChoco = new javax.swing.JLabel();
        lblDonaAzucar = new javax.swing.JLabel();
        lblChino = new javax.swing.JLabel();
        lblJapones = new javax.swing.JLabel();
        lblMuffin = new javax.swing.JLabel();
        lblChocolatinChoco = new javax.swing.JLabel();
        lblChocolatinBlanco = new javax.swing.JLabel();
        lblDomino = new javax.swing.JLabel();
        lblDominoChoco = new javax.swing.JLabel();
        lblRebanada = new javax.swing.JLabel();
        lblCarioca = new javax.swing.JLabel();
        lblBarquillo = new javax.swing.JLabel();
        lblRolCanela = new javax.swing.JLabel();
        lblDonaGlaseada = new javax.swing.JLabel();
        txtDonaGlaseada = new javax.swing.JTextField();
        txtDonaMoka = new javax.swing.JTextField();
        txtDonaChoco = new javax.swing.JTextField();
        txtDonaAzucar = new javax.swing.JTextField();
        txtJapones = new javax.swing.JTextField();
        txtMuffin = new javax.swing.JTextField();
        txtChocolatinChoco = new javax.swing.JTextField();
        txtChocolatinBlanco = new javax.swing.JTextField();
        txtDomino = new javax.swing.JTextField();
        txtRebanada = new javax.swing.JTextField();
        txtDominoChoco = new javax.swing.JTextField();
        txtCarioca = new javax.swing.JTextField();
        txtBarquillo = new javax.swing.JTextField();
        txtRolCanela = new javax.swing.JTextField();
        txtChino = new javax.swing.JTextField();
        lblTrenza = new javax.swing.JLabel();
        lblPeineta = new javax.swing.JLabel();
        lblOreja = new javax.swing.JLabel();
        lblAbanico = new javax.swing.JLabel();
        lblTaco = new javax.swing.JLabel();
        lblCanasta = new javax.swing.JLabel();
        lblPiña = new javax.swing.JLabel();
        lblEmpanadaFeite = new javax.swing.JLabel();
        lblMoñoFeite = new javax.swing.JLabel();
        lblCuadro = new javax.swing.JLabel();
        lblBanderilla = new javax.swing.JLabel();
        lblCampechana = new javax.swing.JLabel();
        lblPonciano = new javax.swing.JLabel();
        lblOjo = new javax.swing.JLabel();
        lblBudin = new javax.swing.JLabel();
        txtTrenza = new javax.swing.JTextField();
        txtPeineta = new javax.swing.JTextField();
        txtOreja = new javax.swing.JTextField();
        txtAbanico = new javax.swing.JTextField();
        txtTaco = new javax.swing.JTextField();
        txtOjo = new javax.swing.JTextField();
        txtPiña = new javax.swing.JTextField();
        txtEmpanadaFeite = new javax.swing.JTextField();
        txtCuadro = new javax.swing.JTextField();
        txtMoñoFeite = new javax.swing.JTextField();
        txtBanderilla = new javax.swing.JTextField();
        txtCampechana = new javax.swing.JTextField();
        txtPonciano = new javax.swing.JTextField();
        txtBudin = new javax.swing.JTextField();
        txtCanasta = new javax.swing.JTextField();
        lblPanDulce = new javax.swing.JLabel();
        lblPolvoron = new javax.swing.JLabel();
        lblPolvoronMazapan = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPiezasPB = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblTotalPD = new javax.swing.JLabel();
        lblPiezasPD = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 214, 155));

        jPanel2.setBackground(new java.awt.Color(165, 105, 66));

        lblListaPedido.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        lblListaPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPedido.setText("- Lista de Pedido -");

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha");

        lblFecha.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(lblListaPedido)
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        cmbCliente.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator1.setBackground(new java.awt.Color(165, 105, 66));
        jSeparator1.setForeground(new java.awt.Color(165, 105, 66));

        lblPanBlanco.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPanBlanco.setText("PAN BLANCO");

        lblTeleras.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblTeleras.setText("Teleras");

        lblBolilloLiso.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblBolilloLiso.setText("Bolillo liso");

        lblBolilloAjonjoli.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblBolilloAjonjoli.setText("Bolillo ajonjolí");

        lblTotalPanBlanco.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        lblTotalPanBlanco.setText("TOTAL DE PAN BLANCO");

        jSeparator2.setBackground(new java.awt.Color(165, 105, 66));
        jSeparator2.setForeground(new java.awt.Color(165, 105, 66));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblConchaBlanca.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblConchaBlanca.setText("Concha blanca");

        lblConchaChoco.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblConchaChoco.setText("Concha chocolate");

        lblConchaAmarilla.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblConchaAmarilla.setText("Concha amarilla");

        lblCuernito.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblCuernito.setText("Cuernito");

        lblHojaldra.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblHojaldra.setText("Hojaldra");

        lblBisquet.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblBisquet.setText("Bisquet");

        lblColchon.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblColchon.setText("Colchón");

        lblMantecada.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblMantecada.setText("Mantecada");

        lblBigote.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblBigote.setText("Bigote");

        lblMoño.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblMoño.setText("Moño");

        lblNovia.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblNovia.setText("Novia");

        lblCocol.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblCocol.setText("Cocol");

        lblMordida.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblMordida.setText("Mordida");

        lblPiojosa.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblPiojosa.setText("Piojosa");

        lblCema.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblCema.setText("Cema");

        lblMaria.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblMaria.setText("María");

        lblBeso.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblBeso.setText("Beso");

        lblAlmeja.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblAlmeja.setText("Almeja");

        lblCacahuate.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblCacahuate.setText("Cacahuate");

        lblHueso.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblHueso.setText("Hueso de manteca");

        lblRosca.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblRosca.setText("Rosca de manteca");

        lblEmpanadaBiz.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblEmpanadaBiz.setText("Empanada Bizcocho");

        lblPiedra.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblPiedra.setText("Piedra");

        lblLadrillo.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblLadrillo.setText("Ladrillo");

        lblGalletaE.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblGalletaE.setText("Galleta espejo");

        lblGalletaNuez.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblGalletaNuez.setText("Galleta nuez");

        lblGalletaCho.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblGalletaCho.setText("Galleta chochito");

        lblGendarme.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblGendarme.setText("Gendarme");

        lblDonaMoka.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblDonaMoka.setText("Dona moka");

        lblDonaChoco.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblDonaChoco.setText("Dona chocolate");

        lblDonaAzucar.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblDonaAzucar.setText("Dona azúcar");

        lblChino.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblChino.setText("Chino");

        lblJapones.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblJapones.setText("Japonés");

        lblMuffin.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblMuffin.setText("Muffin ");

        lblChocolatinChoco.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblChocolatinChoco.setText("Chocolatín negro");

        lblChocolatinBlanco.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblChocolatinBlanco.setText("Chocolatín blanco");

        lblDomino.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblDomino.setText("Domino");

        lblDominoChoco.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblDominoChoco.setText("Domino chocolate");

        lblRebanada.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblRebanada.setText("Rebanada");

        lblCarioca.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblCarioca.setText("Carioca");

        lblBarquillo.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblBarquillo.setText("Barquillo");

        lblRolCanela.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblRolCanela.setText("Rol de canela");

        lblDonaGlaseada.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblDonaGlaseada.setText("Dona glaseada");

        lblTrenza.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblTrenza.setText("Trenza");

        lblPeineta.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblPeineta.setText("Peineta");

        lblOreja.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblOreja.setText("Oreja");

        lblAbanico.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblAbanico.setText("Abanico");

        lblTaco.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblTaco.setText("Taco");

        lblCanasta.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblCanasta.setText("Canasta");

        lblPiña.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblPiña.setText("Piña");

        lblEmpanadaFeite.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblEmpanadaFeite.setText("Empanada feite");

        lblMoñoFeite.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblMoñoFeite.setText("Moño feite");

        lblCuadro.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblCuadro.setText("Cuadro");

        lblBanderilla.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblBanderilla.setText("Banderilla");

        lblCampechana.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblCampechana.setText("Campechana");

        lblPonciano.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblPonciano.setText("Ponciano");

        lblOjo.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblOjo.setText("Ojo");

        lblBudin.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblBudin.setText("Budín");

        lblPanDulce.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPanDulce.setText("PAN DULCE");

        lblPolvoron.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblPolvoron.setText("Polvorón");

        lblPolvoronMazapan.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        lblPolvoronMazapan.setText("Polvorón mazapan");

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuernito.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione el cliente de reparto al que se le realizará la lista de pedido");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel3.setText("Llene los campos correspondientes para pan blanco y pan de dulce, ingresando las piezas que desea de cada clase");

        lblPiezasPB.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPiezasPB.setText("0");

        btnCalcular.setBackground(new java.awt.Color(165, 105, 66));
        btnCalcular.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblTotalPD.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        lblTotalPD.setText("TOTAL DE PAN DULCE");

        lblPiezasPD.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPiezasPD.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(36, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBolilloLiso)
                                            .addComponent(lblBolilloAjonjoli)
                                            .addComponent(lblTeleras))
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtBolilloLiso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTeleras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBolilloAjonjoli, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPanBlanco)
                                        .addGap(59, 59, 59))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTotalPanBlanco)
                                            .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTotalPD)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(btnCalcular))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(lblPiezasPB)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPiezasPD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblConchaChoco)
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCocol, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMordida, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNovia, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMoño, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblBigote, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMantecada, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblColchon, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblHojaldra, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblBisquet, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCuernito, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblBeso, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMaria, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblConchaBlanca, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblConchaAmarilla, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPiojosa, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCema, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPonciano, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPolvoron, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPolvoron)
                                    .addComponent(txtCema)
                                    .addComponent(txtPiojosa)
                                    .addComponent(txtMordida)
                                    .addComponent(txtCocol)
                                    .addComponent(txtNovia)
                                    .addComponent(txtMoño)
                                    .addComponent(txtBigote)
                                    .addComponent(txtMantecada)
                                    .addComponent(txtColchon)
                                    .addComponent(txtBisquet)
                                    .addComponent(txtHojaldra)
                                    .addComponent(txtCuernito)
                                    .addComponent(txtConchaAmarilla)
                                    .addComponent(txtConchaChoco)
                                    .addComponent(txtBeso, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(txtMaria)
                                    .addComponent(txtConchaBlanca)
                                    .addComponent(txtPonciano)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPolvoronMazapan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPolvoronMazapan)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDonaAzucar)
                                .addGap(57, 57, 57)
                                .addComponent(txtDonaAzucar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txtBudin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLadrillo)
                                    .addComponent(lblPiedra)
                                    .addComponent(lblDonaChoco)
                                    .addComponent(lblEmpanadaBiz))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonaChoco)
                                    .addComponent(txtCuadro)
                                    .addComponent(txtLadrillo)
                                    .addComponent(txtPiedra)
                                    .addComponent(txtEmpanadaBiz)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDonaMoka)
                                .addGap(64, 64, 64)
                                .addComponent(txtDonaMoka))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMoñoFeite)
                                .addGap(67, 67, 67)
                                .addComponent(txtMoñoFeite))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDonaGlaseada)
                                .addGap(45, 45, 45)
                                .addComponent(txtDonaGlaseada))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBanderilla)
                                .addGap(74, 74, 74)
                                .addComponent(txtBanderilla))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCampechana)
                                .addGap(56, 56, 56)
                                .addComponent(txtCampechana))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGalletaNuez)
                                    .addComponent(lblCuadro)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblRosca)
                                                .addComponent(lblGalletaE)
                                                .addComponent(lblGalletaCho)
                                                .addComponent(lblHueso)
                                                .addComponent(lblCacahuate))
                                            .addGap(20, 20, 20)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtGalletaCho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                                .addComponent(txtGalletaE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                                .addComponent(txtGalletaNuez, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                                .addComponent(txtCacahuate)
                                                .addComponent(txtHueso)
                                                .addComponent(txtRosca)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblGendarme)
                                                .addComponent(lblAlmeja))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtAlmeja)
                                                .addComponent(txtGendarme, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))))
                                    .addComponent(lblBudin))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDominoChoco)
                                    .addComponent(lblCarioca)
                                    .addComponent(lblRebanada))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDominoChoco)
                                    .addComponent(txtCarioca)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtRebanada, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblChino)
                                    .addComponent(lblRolCanela)
                                    .addComponent(lblBarquillo)
                                    .addComponent(lblChocolatinBlanco)
                                    .addComponent(lblTaco)
                                    .addComponent(lblChocolatinChoco)
                                    .addComponent(lblOjo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtOjo, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(txtChocolatinBlanco)
                                        .addComponent(txtBarquillo)
                                        .addComponent(txtRolCanela)
                                        .addComponent(txtChino)
                                        .addComponent(txtTaco))
                                    .addComponent(txtChocolatinChoco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmpanadaFeite)
                                    .addComponent(lblTrenza)
                                    .addComponent(lblPeineta)
                                    .addComponent(lblOreja))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOreja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPeineta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrenza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmpanadaFeite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDomino, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDomino, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPiña)
                                    .addComponent(lblMuffin)
                                    .addComponent(lblAbanico)
                                    .addComponent(lblJapones))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMuffin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJapones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAbanico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPiña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCanasta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCanasta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(lblPanDulce)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPanDulce)
                            .addComponent(lblPanBlanco))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtBeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBeso))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblGalletaE)
                                        .addComponent(lblPiña)
                                        .addComponent(txtPiña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGalletaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(txtTeleras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblTeleras)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtMaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblMaria))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmpanadaFeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtBolilloLiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBolilloLiso))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblBolilloAjonjoli)
                                            .addComponent(txtBolilloAjonjoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addComponent(lblTotalPanBlanco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPiezasPB)
                                        .addGap(29, 29, 29)
                                        .addComponent(lblTotalPD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPiezasPD)
                                        .addGap(41, 41, 41)
                                        .addComponent(btnCalcular)
                                        .addGap(35, 35, 35)
                                        .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtRosca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblMuffin))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtConchaBlanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblConchaBlanca))
                                                    .addComponent(txtTrenza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtConchaChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblConchaChoco)
                                                    .addComponent(lblGendarme)
                                                    .addComponent(txtGendarme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPeineta)
                                                    .addComponent(txtPeineta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtConchaAmarilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblConchaAmarilla)
                                                    .addComponent(lblAlmeja)
                                                    .addComponent(txtAlmeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblOreja)
                                                    .addComponent(txtOreja, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtCuernito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblCuernito)
                                                    .addComponent(lblCacahuate)
                                                    .addComponent(txtCacahuate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblAbanico)
                                                    .addComponent(txtAbanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtHojaldra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblHojaldra)
                                                    .addComponent(lblHueso)
                                                    .addComponent(txtHueso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblJapones)
                                                    .addComponent(txtJapones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtBisquet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblBisquet)
                                                        .addComponent(lblRosca))
                                                    .addComponent(txtMuffin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtColchon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblColchon))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblEmpanadaBiz)
                                                        .addComponent(txtEmpanadaBiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblChocolatinChoco)
                                                        .addComponent(txtChocolatinChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDomino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtMantecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblPiedra)
                                                .addComponent(lblMantecada))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDomino)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtBigote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblLadrillo))
                                                    .addComponent(lblBigote, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtMoño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMoñoFeite)
                                                    .addComponent(lblMoño))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtNovia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblCuadro)
                                                    .addComponent(lblNovia))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtCocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblBanderilla)
                                                    .addComponent(lblCocol))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtMordida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMordida)
                                                    .addComponent(lblCampechana)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtBarquillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(txtCarioca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(6, 6, 6))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtLadrillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lblChocolatinBlanco)
                                                                .addComponent(txtChocolatinBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtMoñoFeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lblRebanada)
                                                                .addComponent(txtRebanada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lblDominoChoco)
                                                                .addComponent(txtDominoChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtBanderilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lblCarioca))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtCampechana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblBarquillo)))))
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPiojosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDonaGlaseada)
                                            .addComponent(txtDonaGlaseada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblRolCanela)
                                            .addComponent(txtRolCanela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPiojosa))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDonaMoka)
                                            .addComponent(txtDonaMoka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblChino)
                                            .addComponent(txtChino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCema))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPonciano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDonaChoco)
                                            .addComponent(txtDonaChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTaco)
                                            .addComponent(txtTaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPonciano))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtBudin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblOjo)
                                                    .addComponent(txtOjo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblPolvoron)
                                                    .addComponent(txtPolvoron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblDonaAzucar)
                                                    .addComponent(txtDonaAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblCanasta)
                                                    .addComponent(txtCanasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblPolvoronMazapan)
                                                    .addComponent(txtPolvoronMazapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblBudin)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGalletaCho)
                                    .addComponent(txtGalletaCho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpanadaFeite))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGalletaNuez)
                                    .addComponent(lblTrenza)
                                    .addComponent(txtGalletaNuez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
     
lblPiezasPB.setText(String.valueOf(SumaPiezasPB()));

lblPiezasPD.setText(String.valueOf(SumaPiezasPD()));
    }//GEN-LAST:event_btnCalcularActionPerformed

//------------------------------------------------------------------------------
    //Método para generar la fecha 
//------------------------------------------------------------------------------
    private void Fecha(){

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
String fechaActual = sdf.format(new Date());
lblFecha.setText(fechaActual);

}    
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para llenar el comboBox
//------------------------------------------------------------------------------
 
public void llenarComboBox(JComboBox<String> comboBox, Connection conn) {
    String sql = "SELECT CR_Nombre, CR_Telefono FROM clientereparto"; 
    Connection con = Conexion.conectar();
     
    try (PreparedStatement stmt = con.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        comboBox.removeAllItems(); // Limpiar el JComboBox antes de llenarlo
        comboBox.addItem("Seleccione un cliente...");

        while (rs.next()) {
            String nombre = rs.getString("CR_Nombre");
            String telefono = rs.getString("CR_Telefono");
            String item = nombre + ", " + telefono; // Concatenar con coma
            comboBox.addItem(item);
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos en el ComboBox.");
    }
}
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
    //Método para limitar a escribir solo números en los Textfield
//------------------------------------------------------------------------------
    private void limitarNumeros(JTextField textField) {
        textField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) { // Solo permite números
                    e.consume(); // Bloquea la entrada si no es un número
                }
            }
        });
    }
//------------------------------------------------------------------------------    

    
//------------------------------------------------------------------------------
    //
//------------------------------------------------------------------------------
    public void TxtFields() {
    JTextField[] campos = {
        txtAbanico, txtAlmeja, txtBanderilla, txtBarquillo, txtBeso, txtBigote,
        txtBisquet, txtBolilloAjonjoli, txtBolilloLiso, txtBudin, txtCacahuate,
        txtCampechana, txtCanasta, txtCarioca, txtCema, txtChino, txtChocolatinBlanco,
        txtChocolatinChoco, txtCocol, txtColchon, txtConchaAmarilla, txtConchaBlanca,
        txtConchaChoco, txtCuadro, txtCuernito, txtDomino, txtDominoChoco, txtDonaAzucar,
        txtDonaChoco, txtDonaGlaseada, txtDonaMoka, txtEmpanadaBiz, txtEmpanadaFeite,
        txtGalletaCho, txtGalletaE, txtGalletaNuez, txtGendarme, txtHojaldra, txtHueso,
        txtJapones, txtLadrillo, txtMantecada, txtMaria, txtMordida, txtMoño, txtMoñoFeite,
        txtMuffin, txtNovia, txtOjo, txtOreja, txtPeineta, txtPiedra, txtPiojosa, txtPiña,
        txtPolvoron, txtPolvoronMazapan, txtPonciano, txtRebanada, txtRolCanela, txtRosca,
        txtTaco, txtTeleras, txtTrenza
    };

    for (JTextField campo : campos) {
        limitarNumeros(campo);
    }
}
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para sumar las piezas de pan blanco
//------------------------------------------------------------------------------
    private int SumaPiezasPB() {
    int totalPiezasPB = 0;

    int totalTeleras = parseEntero(txtTeleras);
    int totalBL = parseEntero(txtBolilloLiso);
    int totalBA = parseEntero(txtBolilloAjonjoli);

    totalPiezasPB = totalTeleras + totalBL + totalBA;
    return totalPiezasPB;
}
//------------------------------------------------------------------------------
    
    private int parseEntero(JTextField campo) {
    String texto = campo.getText().trim();
    if (texto.isEmpty()) {
        campo.setText("0");
        return 0;
    }
    try {
        return Integer.parseInt(texto);
    } catch (NumberFormatException e) {
        campo.setText("0");
        return 0;
    }
}
    
//------------------------------------------------------------------------------
    //Método para sumar las piezas de pan dulce
//------------------------------------------------------------------------------
    private int SumaPiezasPD() {
    int totalPiezasPD = 0;

    JTextField[] campos = {
        txtAbanico, txtAlmeja, txtBanderilla, txtBarquillo, txtBeso, txtBigote,
        txtBisquet, txtBudin, txtCacahuate,
        txtCampechana, txtCanasta, txtCarioca, txtCema, txtChino, txtChocolatinBlanco,
        txtChocolatinChoco, txtCocol, txtColchon, txtConchaAmarilla, txtConchaBlanca,
        txtConchaChoco, txtCuadro, txtCuernito, txtDomino, txtDominoChoco, txtDonaAzucar,
        txtDonaChoco, txtDonaGlaseada, txtDonaMoka, txtEmpanadaBiz, txtEmpanadaFeite,
        txtGalletaCho, txtGalletaE, txtGalletaNuez, txtGendarme, txtHojaldra, txtHueso,
        txtJapones, txtLadrillo, txtMantecada, txtMaria, txtMordida, txtMoño, txtMoñoFeite,
        txtMuffin, txtNovia, txtOjo, txtOreja, txtPeineta, txtPiedra, txtPiojosa, txtPiña,
        txtPolvoron, txtPolvoronMazapan, txtPonciano, txtRebanada, txtRolCanela, txtRosca,
        txtTaco, txtTrenza
    };

    for (JTextField campo : campos) {
        totalPiezasPD += parseEntero(campo);
    }

    return totalPiezasPD;
}
//------------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAbanico;
    private javax.swing.JLabel lblAlmeja;
    private javax.swing.JLabel lblBanderilla;
    private javax.swing.JLabel lblBarquillo;
    private javax.swing.JLabel lblBeso;
    private javax.swing.JLabel lblBigote;
    private javax.swing.JLabel lblBisquet;
    private javax.swing.JLabel lblBolilloAjonjoli;
    private javax.swing.JLabel lblBolilloLiso;
    private javax.swing.JLabel lblBudin;
    private javax.swing.JLabel lblCacahuate;
    private javax.swing.JLabel lblCampechana;
    private javax.swing.JLabel lblCanasta;
    private javax.swing.JLabel lblCarioca;
    private javax.swing.JLabel lblCema;
    private javax.swing.JLabel lblChino;
    private javax.swing.JLabel lblChocolatinBlanco;
    private javax.swing.JLabel lblChocolatinChoco;
    private javax.swing.JLabel lblCocol;
    private javax.swing.JLabel lblColchon;
    private javax.swing.JLabel lblConchaAmarilla;
    private javax.swing.JLabel lblConchaBlanca;
    private javax.swing.JLabel lblConchaChoco;
    private javax.swing.JLabel lblCuadro;
    private javax.swing.JLabel lblCuernito;
    private javax.swing.JLabel lblDomino;
    private javax.swing.JLabel lblDominoChoco;
    private javax.swing.JLabel lblDonaAzucar;
    private javax.swing.JLabel lblDonaChoco;
    private javax.swing.JLabel lblDonaGlaseada;
    private javax.swing.JLabel lblDonaMoka;
    private javax.swing.JLabel lblEmpanadaBiz;
    private javax.swing.JLabel lblEmpanadaFeite;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGalletaCho;
    private javax.swing.JLabel lblGalletaE;
    private javax.swing.JLabel lblGalletaNuez;
    private javax.swing.JLabel lblGendarme;
    private javax.swing.JLabel lblHojaldra;
    private javax.swing.JLabel lblHueso;
    private javax.swing.JLabel lblJapones;
    private javax.swing.JLabel lblLadrillo;
    private javax.swing.JLabel lblListaPedido;
    private javax.swing.JLabel lblMantecada;
    private javax.swing.JLabel lblMaria;
    private javax.swing.JLabel lblMordida;
    private javax.swing.JLabel lblMoño;
    private javax.swing.JLabel lblMoñoFeite;
    private javax.swing.JLabel lblMuffin;
    private javax.swing.JLabel lblNovia;
    private javax.swing.JLabel lblOjo;
    private javax.swing.JLabel lblOreja;
    private javax.swing.JLabel lblPanBlanco;
    private javax.swing.JLabel lblPanDulce;
    private javax.swing.JLabel lblPeineta;
    private javax.swing.JLabel lblPiedra;
    private javax.swing.JLabel lblPiezasPB;
    private javax.swing.JLabel lblPiezasPD;
    private javax.swing.JLabel lblPiojosa;
    private javax.swing.JLabel lblPiña;
    private javax.swing.JLabel lblPolvoron;
    private javax.swing.JLabel lblPolvoronMazapan;
    private javax.swing.JLabel lblPonciano;
    private javax.swing.JLabel lblRebanada;
    private javax.swing.JLabel lblRolCanela;
    private javax.swing.JLabel lblRosca;
    private javax.swing.JLabel lblTaco;
    private javax.swing.JLabel lblTeleras;
    private javax.swing.JLabel lblTotalPD;
    private javax.swing.JLabel lblTotalPanBlanco;
    private javax.swing.JLabel lblTrenza;
    private javax.swing.JTextField txtAbanico;
    private javax.swing.JTextField txtAlmeja;
    private javax.swing.JTextField txtBanderilla;
    private javax.swing.JTextField txtBarquillo;
    private javax.swing.JTextField txtBeso;
    private javax.swing.JTextField txtBigote;
    private javax.swing.JTextField txtBisquet;
    private javax.swing.JTextField txtBolilloAjonjoli;
    private javax.swing.JTextField txtBolilloLiso;
    private javax.swing.JTextField txtBudin;
    private javax.swing.JTextField txtCacahuate;
    private javax.swing.JTextField txtCampechana;
    private javax.swing.JTextField txtCanasta;
    private javax.swing.JTextField txtCarioca;
    private javax.swing.JTextField txtCema;
    private javax.swing.JTextField txtChino;
    private javax.swing.JTextField txtChocolatinBlanco;
    private javax.swing.JTextField txtChocolatinChoco;
    private javax.swing.JTextField txtCocol;
    private javax.swing.JTextField txtColchon;
    private javax.swing.JTextField txtConchaAmarilla;
    private javax.swing.JTextField txtConchaBlanca;
    private javax.swing.JTextField txtConchaChoco;
    private javax.swing.JTextField txtCuadro;
    private javax.swing.JTextField txtCuernito;
    private javax.swing.JTextField txtDomino;
    private javax.swing.JTextField txtDominoChoco;
    private javax.swing.JTextField txtDonaAzucar;
    private javax.swing.JTextField txtDonaChoco;
    private javax.swing.JTextField txtDonaGlaseada;
    private javax.swing.JTextField txtDonaMoka;
    private javax.swing.JTextField txtEmpanadaBiz;
    private javax.swing.JTextField txtEmpanadaFeite;
    private javax.swing.JTextField txtGalletaCho;
    private javax.swing.JTextField txtGalletaE;
    private javax.swing.JTextField txtGalletaNuez;
    private javax.swing.JTextField txtGendarme;
    private javax.swing.JTextField txtHojaldra;
    private javax.swing.JTextField txtHueso;
    private javax.swing.JTextField txtJapones;
    private javax.swing.JTextField txtLadrillo;
    private javax.swing.JTextField txtMantecada;
    private javax.swing.JTextField txtMaria;
    private javax.swing.JTextField txtMordida;
    private javax.swing.JTextField txtMoño;
    private javax.swing.JTextField txtMoñoFeite;
    private javax.swing.JTextField txtMuffin;
    private javax.swing.JTextField txtNovia;
    private javax.swing.JTextField txtOjo;
    private javax.swing.JTextField txtOreja;
    private javax.swing.JTextField txtPeineta;
    private javax.swing.JTextField txtPiedra;
    private javax.swing.JTextField txtPiojosa;
    private javax.swing.JTextField txtPiña;
    private javax.swing.JTextField txtPolvoron;
    private javax.swing.JTextField txtPolvoronMazapan;
    private javax.swing.JTextField txtPonciano;
    private javax.swing.JTextField txtRebanada;
    private javax.swing.JTextField txtRolCanela;
    private javax.swing.JTextField txtRosca;
    private javax.swing.JTextField txtTaco;
    private javax.swing.JTextField txtTeleras;
    private javax.swing.JTextField txtTrenza;
    // End of variables declaration//GEN-END:variables
//------------------------------------------------------------------------------
    //Método para imprimir
//------------------------------------------------------------------------------
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        
    if(pageIndex == 0){
    Graphics2D graphics2d=(Graphics2D) graphics;
    graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
    printAll(graphics2d);
    return PAGE_EXISTS;
    }
    else{
    return NO_SUCH_PAGE;
    }
    
    
    }
//------------------------------------------------------------------------------
}
