/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

import ConexionBD.Conexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import com.toedter.calendar.JCalendar;

/**
 *
 * @author Paola Barrera Tenorio 2192007348
 */

public class ConteoPanHorneado extends javax.swing.JFrame {

    /**
     * Creates new form ConteoPanHorneado
     */
    public ConteoPanHorneado() {
        initComponents();
        
        this.setTitle("Panificadora La Izcalli");
        this.setLocationRelativeTo(ConteoPanHorneado.this);
        this.setResizable(false);
        
        Fecha();
        Mostrar("conteo_panhorneado");
        limitarNumeros(txtTotalPB);
        limitarNumeros(txtTotalPD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblConteoPan = new javax.swing.JLabel();
        lblFechaDia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLeyenda = new javax.swing.JLabel();
        btnRegresarCP = new javax.swing.JButton();
        btnGuardarCP = new javax.swing.JButton();
        TodosRegistros = new javax.swing.JButton();
        UltimosRegistros = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPanBlanco = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTotalPiezasPB = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblPanDulce = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblTotalPiezasPD = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotalPB = new javax.swing.JTextField();
        txtTotalPD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConteoPan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 212, 155));
        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 831));

        jPanel2.setBackground(new java.awt.Color(165, 105, 66));

        lblFecha.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));

        lblConteoPan.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        lblConteoPan.setForeground(new java.awt.Color(255, 255, 255));
        lblConteoPan.setText("- Conteo del Pan Horneado -");

        lblFechaDia.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblFechaDia.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaDia.setText("Fecha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblConteoPan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFechaDia)
                        .addGap(105, 105, 105))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblConteoPan)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFechaDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(165, 105, 66));

        lblLeyenda.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        lblLeyenda.setForeground(new java.awt.Color(255, 255, 255));
        lblLeyenda.setText("\"La Izcalli \"");

        btnRegresarCP.setBackground(new java.awt.Color(252, 211, 125));
        btnRegresarCP.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnRegresarCP.setText("Regresar");
        btnRegresarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCPActionPerformed(evt);
            }
        });

        btnGuardarCP.setBackground(new java.awt.Color(252, 211, 125));
        btnGuardarCP.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnGuardarCP.setText("Guardar");
        btnGuardarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCPActionPerformed(evt);
            }
        });

        TodosRegistros.setBackground(new java.awt.Color(252, 211, 125));
        TodosRegistros.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        TodosRegistros.setText("Mostrar todos los registros");
        TodosRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosRegistrosActionPerformed(evt);
            }
        });

        UltimosRegistros.setBackground(new java.awt.Color(252, 211, 125));
        UltimosRegistros.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        UltimosRegistros.setText("Mostrar últimos registros");
        UltimosRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimosRegistrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnRegresarCP))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TodosRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UltimosRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarCP)
                .addGap(220, 220, 220))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarCP)
                    .addComponent(btnGuardarCP)
                    .addComponent(TodosRegistros))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeyenda)
                    .addComponent(UltimosRegistros))
                .addGap(37, 37, 37))
        );

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel3.setText("Para llenar los siguientes campos pida a uno de los empleados que le de la cantidad ");

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel4.setText("*Esta es una forma de corroborar que la cantidad en la lista que se envió a los maestros panaderos coincida con la producción horneada*");

        jSeparator1.setForeground(new java.awt.Color(51, 0, 0));

        lblPanBlanco.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblPanBlanco.setText("PAN BLANCO");

        jSeparator2.setForeground(new java.awt.Color(51, 0, 0));

        lblTotalPiezasPB.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        lblTotalPiezasPB.setText("Total de piezas ");

        jSeparator3.setForeground(new java.awt.Color(51, 0, 0));

        lblPanDulce.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblPanDulce.setText("PAN DULCE");

        jSeparator4.setForeground(new java.awt.Color(51, 0, 0));

        lblTotalPiezasPD.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        lblTotalPiezasPD.setText("Total de piezas");

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        jLabel10.setText("de pan horneado para la venta general");

        txtTotalPB.setText("0");

        txtTotalPD.setText("0");

        TablaConteoPan.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        TablaConteoPan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaConteoPan);

        jLabel1.setText("Ejemplo. 150");

        jLabel2.setText("Ejemplo 300");

        jCalendar1.setMaximumSize(new java.awt.Dimension(100, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(lblPanBlanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPanDulce)
                .addGap(212, 212, 212))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblTotalPiezasPB)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTotalPB, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addComponent(lblTotalPiezasPD)
                                .addGap(36, 36, 36)
                                .addComponent(txtTotalPD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(98, 98, 98))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(96, 96, 96)
                                    .addComponent(jLabel3)
                                    .addGap(34, 34, 34))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(118, 118, 118)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPanBlanco)
                    .addComponent(lblPanDulce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPiezasPB)
                    .addComponent(txtTotalPB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPiezasPD)
                    .addComponent(txtTotalPD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


//Botón para regresar a la interfaz anterior
    private void btnRegresarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCPActionPerformed
        MenuEncargado encargado = new MenuEncargado();
        encargado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarCPActionPerformed

//Botón Guardar
    private void btnGuardarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCPActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarCPActionPerformed


    private void TodosRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosRegistrosActionPerformed
    MostrarTodosRegistros("conteo_panhorneado");
    }//GEN-LAST:event_TodosRegistrosActionPerformed

    private void UltimosRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimosRegistrosActionPerformed
      Mostrar("conteo_panhorneado");
    }//GEN-LAST:event_UltimosRegistrosActionPerformed

//------------------------------------------------------------------------------
    //Método para mostrar los registros de la entidad EQUIPO
//------------------------------------------------------------------------------
    public void Mostrar(String tabla) {
    String sql = "SELECT * FROM " + tabla + " WHERE CPH_Fecha >= NOW() - INTERVAL 3 WEEK";
    Conexion con = new Conexion();
    java.sql.Connection conexion = con.conectar();

    DefaultTableModel model = new DefaultTableModel();
    String[] columnas = {"ID", "Fecha", "Total Piezas Pan Blanco", "Total Piezas Pan Dulce"};

    for (String columna : columnas) {
        model.addColumn(columna);
    }

    TablaConteoPan.setModel(model);

    try (java.sql.Statement st = conexion.createStatement(); ResultSet rs = st.executeQuery(sql)) {
        while (rs.next()) {
            String[] datos = new String[columnas.length];
            for (int i = 0; i < columnas.length; i++) {
                datos[i] = rs.getString(i + 1);
            }

            model.addRow(datos);
        }

        // Ajustar ancho de columnas
        TableColumnModel modeloColumnas = TablaConteoPan.getColumnModel();
        modeloColumnas.getColumn(0).setPreferredWidth(1);  // ID
        modeloColumnas.getColumn(1).setPreferredWidth(10); // Fecha
        modeloColumnas.getColumn(2).setPreferredWidth(10); // Piezas PB
        modeloColumnas.getColumn(3).setPreferredWidth(10); // Piezas PD

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error en executeQuery: " + e.getMessage());
    } finally {
        try {
            if (conexion != null && !conexion.isClosed()) {
                conexion.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + ex.getMessage());
        }
    }
}
//------------------------------------------------------------------------------



//------------------------------------------------------------------------------
    //Método para mostrar todos los regustros de la table
//------------------------------------------------------------------------------
    public void MostrarTodosRegistros(String tabla) {
    String sql = "SELECT * FROM " + tabla;
    Conexion con = new Conexion();
    java.sql.Connection conexion = con.conectar();

    DefaultTableModel model = new DefaultTableModel();
    String[] columnas = {"ID", "Fecha", "Total Piezas Pan Blanco", "Total Piezas Pan Dulce"};
    
    
    for (String columna : columnas) {
        model.addColumn(columna);
    }

    TablaConteoPan.setModel(model);

    try (java.sql.Statement st = conexion.createStatement(); ResultSet rs = st.executeQuery(sql)) {
        while (rs.next()) {
            String[] datos = new String[columnas.length];
            for (int i = 0; i < columnas.length; i++) {
                datos[i] = rs.getString(i + 1);
            }
          
            model.addRow(datos);
        }
        
        // Modificar el ancho de las columnas
        TableColumnModel modeloColumnas = TablaConteoPan.getColumnModel();
        modeloColumnas.getColumn(0).setPreferredWidth(1);  // ID
        modeloColumnas.getColumn(1).setPreferredWidth(10); // Fecha
        modeloColumnas.getColumn(2).setPreferredWidth(10); // Piezas PB
        modeloColumnas.getColumn(3).setPreferredWidth(10); // Piezas PD
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error en executeQuery: " + e.getMessage());
    } finally {
        try {
            if (conexion != null && !conexion.isClosed()) {
                conexion.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + ex.getMessage());
        }
    }
}    
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para guardar los datos en la tabla Conteo Pan Horneado
//------------------------------------------------------------------------------

private void Guardar(){

    Date fecha = parseDate(lblFecha.getText());     
    int totalPB = Integer.parseInt(txtTotalPB.getText()); 
    int totalPD = Integer.parseInt(txtTotalPD.getText());  
    
    if (fecha == null) {
        JOptionPane.showMessageDialog(null, "Fecha inválida. Ingrese en formato yyyy-MM-dd.");
        return; // Sale del método si la fecha es inválida
    }
    
    java.sql.Date fechaSQL = new java.sql.Date(fecha.getTime()); 
    
    try {
        java.sql.Connection con =  Conexion.conectar(); 
        PreparedStatement ps = con.prepareStatement("INSERT INTO conteo_panhorneado (CPH_Fecha, CPH_TotalPiezasPB, CPH_TotalPiezasPD) VALUES (?,?,?)");

        ps.setDate(1, fechaSQL);
        ps.setInt(2, totalPB);
        ps.setInt(3, totalPD); 

        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registro guardado");
        
        //Actualizar la tabla para que aparezca el registro nuevo
        Mostrar("conteo_panhorneado");
        
        //Después de guardar el registro limpiar los campos 
        LimpiarCampos();
        
        con.close(); // Cierra la conexión

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage());
    }

}
//------------------------------------------------------------------------------
    
    
    
//------------------------------------------------------------------------------
    //Método para limitar a escribir solo números en los Textfield
//------------------------------------------------------------------------------
    private void limitarNumeros(JTextField textField) {
        textField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) { // Solo permite números
                    e.consume(); // Bloquea la entrada si no es un número
                }
            }
        });
    }
//------------------------------------------------------------------------------    

    

//------------------------------------------------------------------------------
    //Método para generar la fecha 
//------------------------------------------------------------------------------
private void Fecha(){

    LocalDate hoy = LocalDate.now();
    DateTimeFormatter formatoDia = DateTimeFormatter.ofPattern("EEEE", new Locale("es", "ES"));
    lblFechaDia.setText("Fecha: " + hoy.format(formatoDia));
    
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaActual = sdf.format(new Date());
    lblFecha.setText( fechaActual);
}    
//------------------------------------------------------------------------------    
    
    
//------------------------------------------------------------------------------
    //Método para limpiar los campos
//------------------------------------------------------------------------------
private void LimpiarCampos(){
    
        txtTotalPB.setText("");
        txtTotalPD.setText("");

}
//------------------------------------------------------------------------------ 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConteoPanHorneado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConteoPanHorneado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConteoPanHorneado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConteoPanHorneado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConteoPanHorneado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaConteoPan;
    private javax.swing.JButton TodosRegistros;
    private javax.swing.JButton UltimosRegistros;
    private javax.swing.JButton btnGuardarCP;
    private javax.swing.JButton btnRegresarCP;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblConteoPan;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaDia;
    private javax.swing.JLabel lblLeyenda;
    private javax.swing.JLabel lblPanBlanco;
    private javax.swing.JLabel lblPanDulce;
    private javax.swing.JLabel lblTotalPiezasPB;
    private javax.swing.JLabel lblTotalPiezasPD;
    private javax.swing.JTextField txtTotalPB;
    private javax.swing.JTextField txtTotalPD;
    // End of variables declaration//GEN-END:variables

//------------------------------------------------------------------------------
    //Método de parseo para la fecha 
//------------------------------------------------------------------------------
    private Date parseDate(String fecha) {
         try {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd"); 
        java.util.Date fechaUtil = formato.parse(fecha);
        return new java.sql.Date(fechaUtil.getTime());
    } 
         catch (ParseException e) {
        System.out.println("Error al convertir la fecha: " + e.getMessage());
        return null; // Devuelve null si hay error
    }
    }



}
