/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

/**
 *
 * @author Paola Barrera Tenorio 2192007348
 */

public class EleccionUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EleccionUsuario
     */
    public EleccionUsuario() {
        initComponents();
        
        this.setTitle("Panificadora La Izcalli");
        this.setLocationRelativeTo(EleccionUsuario.this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelArriba = new javax.swing.JPanel();
        lblPanificadora = new javax.swing.JLabel();
        PanelAbajo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblIzcalli = new javax.swing.JLabel();
        PanelEncargado = new javax.swing.JPanel();
        ImagenEncargado = new javax.swing.JLabel();
        PanelCajera = new javax.swing.JPanel();
        ImagenCajera = new javax.swing.JLabel();
        lblEncargado = new javax.swing.JLabel();
        lblCajera = new javax.swing.JLabel();
        btnIngresarEncargado = new javax.swing.JButton();
        btnIngresarCajera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(255, 235, 204));

        PanelArriba.setBackground(new java.awt.Color(217, 161, 102));

        lblPanificadora.setBackground(new java.awt.Color(0, 0, 0));
        lblPanificadora.setFont(new java.awt.Font("Castellar", 0, 48)); // NOI18N
        lblPanificadora.setText("-Panificadora-");

        javax.swing.GroupLayout PanelArribaLayout = new javax.swing.GroupLayout(PanelArriba);
        PanelArriba.setLayout(PanelArribaLayout);
        PanelArribaLayout.setHorizontalGroup(
            PanelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArribaLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(lblPanificadora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelArribaLayout.setVerticalGroup(
            PanelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArribaLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lblPanificadora)
                .addContainerGap())
        );

        PanelAbajo.setBackground(new java.awt.Color(217, 161, 102));

        jLabel3.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        jLabel3.setText("\"La Izcalli\"");

        btnRegresar.setBackground(new java.awt.Color(252, 211, 125));
        btnRegresar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAbajoLayout = new javax.swing.GroupLayout(PanelAbajo);
        PanelAbajo.setLayout(PanelAbajoLayout);
        PanelAbajoLayout.setHorizontalGroup(
            PanelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAbajoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(59, 59, 59))
        );
        PanelAbajoLayout.setVerticalGroup(
            PanelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAbajoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(PanelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33))
        );

        lblIzcalli.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        lblIzcalli.setText("\"La Izcalli\"");

        PanelEncargado.setBackground(new java.awt.Color(255, 255, 255));

        ImagenEncargado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Encargado.png"))); // NOI18N

        javax.swing.GroupLayout PanelEncargadoLayout = new javax.swing.GroupLayout(PanelEncargado);
        PanelEncargado.setLayout(PanelEncargadoLayout);
        PanelEncargadoLayout.setHorizontalGroup(
            PanelEncargadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEncargadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelEncargadoLayout.setVerticalGroup(
            PanelEncargadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEncargadoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ImagenEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        PanelCajera.setBackground(new java.awt.Color(255, 255, 255));

        ImagenCajera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cajera.png"))); // NOI18N
        ImagenCajera.setText("jLabel6");

        javax.swing.GroupLayout PanelCajeraLayout = new javax.swing.GroupLayout(PanelCajera);
        PanelCajera.setLayout(PanelCajeraLayout);
        PanelCajeraLayout.setHorizontalGroup(
            PanelCajeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCajeraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenCajera, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelCajeraLayout.setVerticalGroup(
            PanelCajeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCajeraLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ImagenCajera, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        lblEncargado.setFont(new java.awt.Font("Bell MT", 0, 48)); // NOI18N
        lblEncargado.setText("Encargado");

        lblCajera.setFont(new java.awt.Font("Bell MT", 0, 48)); // NOI18N
        lblCajera.setText("Cajera");

        btnIngresarEncargado.setBackground(new java.awt.Color(165, 105, 66));
        btnIngresarEncargado.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnIngresarEncargado.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarEncargado.setText("Ingresar");
        btnIngresarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEncargadoActionPerformed(evt);
            }
        });

        btnIngresarCajera.setBackground(new java.awt.Color(165, 105, 66));
        btnIngresarCajera.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnIngresarCajera.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarCajera.setText("Ingresar");
        btnIngresarCajera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCajeraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelAbajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(PanelEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(PanelCajera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblEncargado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCajera)
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btnIngresarEncargado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresarCajera)
                .addGap(224, 224, 224))
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(lblIzcalli, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PanelArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIzcalli)
                .addGap(43, 43, 43)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCajera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncargado)
                    .addComponent(lblCajera))
                .addGap(18, 18, 18)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarCajera)
                    .addComponent(btnIngresarEncargado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(PanelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Botón IngresarEncargado
    private void btnIngresarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEncargadoActionPerformed
        LoginEncargado encargado = new LoginEncargado();
        encargado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngresarEncargadoActionPerformed

//Botón Ingresar Cajera
    private void btnIngresarCajeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCajeraActionPerformed
        LoginCajera cajera = new LoginCajera();
        cajera.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngresarCajeraActionPerformed

//Botón Regresar
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Portada p = new Portada();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EleccionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EleccionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EleccionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EleccionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EleccionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenCajera;
    private javax.swing.JLabel ImagenEncargado;
    private javax.swing.JPanel PanelAbajo;
    private javax.swing.JPanel PanelArriba;
    private javax.swing.JPanel PanelCajera;
    private javax.swing.JPanel PanelEncargado;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnIngresarCajera;
    private javax.swing.JButton btnIngresarEncargado;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCajera;
    private javax.swing.JLabel lblEncargado;
    private javax.swing.JLabel lblIzcalli;
    private javax.swing.JLabel lblPanificadora;
    // End of variables declaration//GEN-END:variables
}
