/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

/**
 *
 * @author Paola Barrera Tenorio 2192007348
 */

public class MenuInventario extends javax.swing.JFrame {

    /**
     * Creates new form MenuInventario
     */
    public MenuInventario() {
        initComponents();
        
        this.setTitle("Panificadora La Izcalli");
        this.setLocationRelativeTo(MenuInventario.this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblInventario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLeyendaI = new javax.swing.JLabel();
        lblSeleccionar = new javax.swing.JLabel();
        btnIngredientesI = new javax.swing.JButton();
        btnEquipoI = new javax.swing.JButton();
        btnHerramientasI = new javax.swing.JButton();
        btnMaterialesEmpaqueI = new javax.swing.JButton();
        btnLimpiezaMantenimientoI = new javax.swing.JButton();
        btnMobiliarioI = new javax.swing.JButton();
        btnRegresarI = new javax.swing.JButton();
        btnCerrarSesionI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 245, 225));

        jPanel2.setBackground(new java.awt.Color(1, 87, 155));

        lblInventario.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        lblInventario.setForeground(new java.awt.Color(255, 255, 255));
        lblInventario.setText("- Inventario -");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(lblInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblInventario)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(1, 87, 155));

        lblLeyendaI.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        lblLeyendaI.setForeground(new java.awt.Color(255, 255, 255));
        lblLeyendaI.setText("\"La Izcalli\"");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblLeyendaI, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblLeyendaI)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        lblSeleccionar.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        lblSeleccionar.setText("Seleccione la categoría del inventario a la que desea ingresar");

        btnIngredientesI.setBackground(new java.awt.Color(176, 212, 235));
        btnIngredientesI.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        btnIngredientesI.setText("Ingredientes");
        btnIngredientesI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientesIActionPerformed(evt);
            }
        });

        btnEquipoI.setBackground(new java.awt.Color(176, 212, 235));
        btnEquipoI.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        btnEquipoI.setText("Equipo");
        btnEquipoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoIActionPerformed(evt);
            }
        });

        btnHerramientasI.setBackground(new java.awt.Color(176, 212, 235));
        btnHerramientasI.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        btnHerramientasI.setText("Herramientas");
        btnHerramientasI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHerramientasIActionPerformed(evt);
            }
        });

        btnMaterialesEmpaqueI.setBackground(new java.awt.Color(176, 212, 235));
        btnMaterialesEmpaqueI.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        btnMaterialesEmpaqueI.setText("Materiales de Empaque");
        btnMaterialesEmpaqueI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialesEmpaqueIActionPerformed(evt);
            }
        });

        btnLimpiezaMantenimientoI.setBackground(new java.awt.Color(176, 212, 235));
        btnLimpiezaMantenimientoI.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        btnLimpiezaMantenimientoI.setText("Limpieza y Mantenimiento");
        btnLimpiezaMantenimientoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiezaMantenimientoIActionPerformed(evt);
            }
        });

        btnMobiliarioI.setBackground(new java.awt.Color(176, 212, 235));
        btnMobiliarioI.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        btnMobiliarioI.setText("Mobiliario");
        btnMobiliarioI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobiliarioIActionPerformed(evt);
            }
        });

        btnRegresarI.setBackground(new java.awt.Color(1, 87, 155));
        btnRegresarI.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnRegresarI.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarI.setText("Regresar");
        btnRegresarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarIActionPerformed(evt);
            }
        });

        btnCerrarSesionI.setBackground(new java.awt.Color(1, 87, 155));
        btnCerrarSesionI.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnCerrarSesionI.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesionI.setText("Cerrar Sesión");
        btnCerrarSesionI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnRegresarI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesionI)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(btnEquipoI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(btnMobiliarioI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(btnHerramientasI, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 217, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSeleccionar)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIngredientesI)
                        .addGap(404, 404, 404))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMaterialesEmpaqueI)
                        .addGap(325, 325, 325))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimpiezaMantenimientoI)
                        .addGap(298, 298, 298))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblSeleccionar)
                .addGap(34, 34, 34)
                .addComponent(btnEquipoI)
                .addGap(18, 18, 18)
                .addComponent(btnMobiliarioI)
                .addGap(18, 18, 18)
                .addComponent(btnIngredientesI)
                .addGap(18, 18, 18)
                .addComponent(btnHerramientasI)
                .addGap(18, 18, 18)
                .addComponent(btnMaterialesEmpaqueI)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiezaMantenimientoI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarI)
                    .addComponent(btnCerrarSesionI))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Botón Mobiliario
    private void btnMobiliarioIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobiliarioIActionPerformed
        Mobiliario mobiliario = new Mobiliario();
        mobiliario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMobiliarioIActionPerformed

//Botón Regresar 
    private void btnRegresarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarIActionPerformed
        MenuEncargado encargado = new MenuEncargado();
        encargado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarIActionPerformed

//Botón Cerrar Sesión
    private void btnCerrarSesionIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionIActionPerformed
        EleccionUsuario usuario = new EleccionUsuario();
        usuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSesionIActionPerformed

//Botón Equipo
    private void btnEquipoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoIActionPerformed
        Equipo equipo = new Equipo();
        equipo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEquipoIActionPerformed

//Botón Ingredientes
    private void btnIngredientesIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientesIActionPerformed
        Ingredientes ingredientes = new Ingredientes();
        ingredientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngredientesIActionPerformed

//Botón Herramientas
    private void btnHerramientasIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHerramientasIActionPerformed
        Herramientas herramienta = new Herramientas();
        herramienta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHerramientasIActionPerformed

//Botón Materiales Empaque
    private void btnMaterialesEmpaqueIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialesEmpaqueIActionPerformed
        MaterialesEmpaque materiales = new MaterialesEmpaque();
        materiales.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMaterialesEmpaqueIActionPerformed

//Botón Limpieza y Mantenimiento
    private void btnLimpiezaMantenimientoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiezaMantenimientoIActionPerformed
        LimpiezaYMantenimiento limpieza = new LimpiezaYMantenimiento();
        limpieza.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLimpiezaMantenimientoIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesionI;
    private javax.swing.JButton btnEquipoI;
    private javax.swing.JButton btnHerramientasI;
    private javax.swing.JButton btnIngredientesI;
    private javax.swing.JButton btnLimpiezaMantenimientoI;
    private javax.swing.JButton btnMaterialesEmpaqueI;
    private javax.swing.JButton btnMobiliarioI;
    private javax.swing.JButton btnRegresarI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblLeyendaI;
    private javax.swing.JLabel lblSeleccionar;
    // End of variables declaration//GEN-END:variables
}
