/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

/**
 *
 * @author Paola Barrera Tenorio 2192007348
 */
public class MenuEncargado extends javax.swing.JFrame {

    /**
     * Creates new form MenuEncargado
     */
    public MenuEncargado() {
        initComponents();
        
        this.setTitle("Panificadora La Izcalli");
        this.setLocationRelativeTo(MenuEncargado.this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelArriba = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        PanelAbajo = new javax.swing.JPanel();
        btnCSME = new javax.swing.JButton();
        lblLeyenda = new javax.swing.JLabel();
        Panel_PB = new javax.swing.JPanel();
        ImagenPB = new javax.swing.JLabel();
        Panel_PD = new javax.swing.JPanel();
        ImagenPD = new javax.swing.JLabel();
        Panel_CP = new javax.swing.JPanel();
        ImagenCP = new javax.swing.JLabel();
        Panel_CR = new javax.swing.JPanel();
        ImagenCR = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Panel_RV = new javax.swing.JPanel();
        ImagenRV = new javax.swing.JLabel();
        Panel_I = new javax.swing.JPanel();
        ImagenI = new javax.swing.JLabel();
        btn_PB = new javax.swing.JButton();
        btn_PD = new javax.swing.JButton();
        btn_CP = new javax.swing.JButton();
        btn_I = new javax.swing.JButton();
        btn_CR = new javax.swing.JButton();
        btn_RV = new javax.swing.JButton();
        lblPB = new javax.swing.JLabel();
        lblPD = new javax.swing.JLabel();
        lblCP = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        lblCR = new javax.swing.JLabel();
        lblRV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));

        PanelFondo.setBackground(new java.awt.Color(255, 235, 204));

        PanelArriba.setBackground(new java.awt.Color(165, 105, 66));

        lblBienvenido.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("¡iBienvenido Encargado!");

        javax.swing.GroupLayout PanelArribaLayout = new javax.swing.GroupLayout(PanelArriba);
        PanelArriba.setLayout(PanelArribaLayout);
        PanelArribaLayout.setHorizontalGroup(
            PanelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArribaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        PanelArribaLayout.setVerticalGroup(
            PanelArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArribaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblBienvenido)
                .addGap(16, 16, 16))
        );

        PanelAbajo.setBackground(new java.awt.Color(217, 161, 102));

        btnCSME.setBackground(new java.awt.Color(252, 211, 125));
        btnCSME.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnCSME.setText("Cerrar Sesión");
        btnCSME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSMEActionPerformed(evt);
            }
        });

        lblLeyenda.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        lblLeyenda.setForeground(new java.awt.Color(255, 255, 255));
        lblLeyenda.setText("\"La izcalli\"");

        javax.swing.GroupLayout PanelAbajoLayout = new javax.swing.GroupLayout(PanelAbajo);
        PanelAbajo.setLayout(PanelAbajoLayout);
        PanelAbajoLayout.setHorizontalGroup(
            PanelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAbajoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCSME)
                .addGap(65, 65, 65))
        );
        PanelAbajoLayout.setVerticalGroup(
            PanelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAbajoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCSME)
                    .addComponent(lblLeyenda))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Panel_PB.setBackground(new java.awt.Color(255, 189, 89));

        ImagenPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PanBlanco.png"))); // NOI18N

        javax.swing.GroupLayout Panel_PBLayout = new javax.swing.GroupLayout(Panel_PB);
        Panel_PB.setLayout(Panel_PBLayout);
        Panel_PBLayout.setHorizontalGroup(
            Panel_PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PBLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(ImagenPB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        Panel_PBLayout.setVerticalGroup(
            Panel_PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PBLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ImagenPB, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_PD.setBackground(new java.awt.Color(255, 189, 89));

        ImagenPD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PanDulce.png"))); // NOI18N

        javax.swing.GroupLayout Panel_PDLayout = new javax.swing.GroupLayout(Panel_PD);
        Panel_PD.setLayout(Panel_PDLayout);
        Panel_PDLayout.setHorizontalGroup(
            Panel_PDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PDLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ImagenPD)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        Panel_PDLayout.setVerticalGroup(
            Panel_PDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenPD, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        Panel_CP.setBackground(new java.awt.Color(255, 189, 89));

        ImagenCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConteoPan.png"))); // NOI18N

        javax.swing.GroupLayout Panel_CPLayout = new javax.swing.GroupLayout(Panel_CP);
        Panel_CP.setLayout(Panel_CPLayout);
        Panel_CPLayout.setHorizontalGroup(
            Panel_CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CPLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ImagenCP)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        Panel_CPLayout.setVerticalGroup(
            Panel_CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CPLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ImagenCP, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_CR.setBackground(new java.awt.Color(255, 189, 89));

        ImagenCR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel7.setText("Reparto");

        javax.swing.GroupLayout Panel_CRLayout = new javax.swing.GroupLayout(Panel_CR);
        Panel_CR.setLayout(Panel_CRLayout);
        Panel_CRLayout.setHorizontalGroup(
            Panel_CRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CRLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(Panel_CRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(ImagenCR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_CRLayout.setVerticalGroup(
            Panel_CRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_CRLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenCR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        Panel_RV.setBackground(new java.awt.Color(255, 189, 89));

        ImagenRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportesVenta.png"))); // NOI18N

        javax.swing.GroupLayout Panel_RVLayout = new javax.swing.GroupLayout(Panel_RV);
        Panel_RV.setLayout(Panel_RVLayout);
        Panel_RVLayout.setHorizontalGroup(
            Panel_RVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RVLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ImagenRV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_RVLayout.setVerticalGroup(
            Panel_RVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenRV, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        Panel_I.setBackground(new java.awt.Color(255, 189, 89));

        ImagenI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario.png"))); // NOI18N

        javax.swing.GroupLayout Panel_ILayout = new javax.swing.GroupLayout(Panel_I);
        Panel_I.setLayout(Panel_ILayout);
        Panel_ILayout.setHorizontalGroup(
            Panel_ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ILayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ImagenI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_ILayout.setVerticalGroup(
            Panel_ILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ILayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(ImagenI, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        btn_PB.setBackground(new java.awt.Color(165, 105, 66));
        btn_PB.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_PB.setForeground(new java.awt.Color(255, 255, 255));
        btn_PB.setText("Entrar");
        btn_PB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PBActionPerformed(evt);
            }
        });

        btn_PD.setBackground(new java.awt.Color(165, 105, 66));
        btn_PD.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_PD.setForeground(new java.awt.Color(255, 255, 255));
        btn_PD.setText("Entrar");
        btn_PD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PDActionPerformed(evt);
            }
        });

        btn_CP.setBackground(new java.awt.Color(165, 105, 66));
        btn_CP.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_CP.setForeground(new java.awt.Color(255, 255, 255));
        btn_CP.setText("Entrar");
        btn_CP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CPActionPerformed(evt);
            }
        });

        btn_I.setBackground(new java.awt.Color(165, 105, 66));
        btn_I.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_I.setForeground(new java.awt.Color(255, 255, 255));
        btn_I.setText("Entrar");
        btn_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IActionPerformed(evt);
            }
        });

        btn_CR.setBackground(new java.awt.Color(165, 105, 66));
        btn_CR.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_CR.setForeground(new java.awt.Color(255, 255, 255));
        btn_CR.setText("Entrar");
        btn_CR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CRActionPerformed(evt);
            }
        });

        btn_RV.setBackground(new java.awt.Color(165, 105, 66));
        btn_RV.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_RV.setForeground(new java.awt.Color(255, 255, 255));
        btn_RV.setText("Entrar");
        btn_RV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RVActionPerformed(evt);
            }
        });

        lblPB.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        lblPB.setText("Pan Blanco");

        lblPD.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        lblPD.setText("Pan Dulce");

        lblCP.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        lblCP.setText("Conteo del Pan");

        lblI.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        lblI.setText("Inventario");

        lblCR.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        lblCR.setText("Clientes de ");

        lblRV.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        lblRV.setText("Reportes de Venta");

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelAbajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_PB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_I, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_CR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_PD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_CP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_RV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblPB)
                .addGap(143, 143, 143)
                .addComponent(lblPD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(lblCP)
                .addGap(68, 68, 68))
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btn_PB)
                .addGap(246, 246, 246)
                .addComponent(btn_PD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CP)
                .addGap(152, 152, 152))
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(lblI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCR)
                .addGap(69, 69, 69)
                .addComponent(lblRV)
                .addGap(42, 42, 42))
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btn_I)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CR)
                .addGap(233, 233, 233)
                .addComponent(btn_RV)
                .addGap(146, 146, 146))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PanelArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPD)
                    .addComponent(lblCP)
                    .addComponent(lblPB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_PB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_PD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_CP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_PB)
                    .addComponent(btn_PD)
                    .addComponent(btn_CP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblI)
                    .addComponent(lblCR)
                    .addComponent(lblRV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Panel_CR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(Panel_I, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_RV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_I)
                    .addComponent(btn_CR)
                    .addComponent(btn_RV))
                .addGap(18, 18, 18)
                .addComponent(PanelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Botón Cerrar Sesión
    private void btnCSMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSMEActionPerformed
        EleccionUsuario usuario = new EleccionUsuario();
        usuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCSMEActionPerformed

//Botón Pan Blanco
    private void btn_PBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PBActionPerformed
        PanBlanco pb = new PanBlanco();
        pb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_PBActionPerformed

//Botón Pan Dulce
    private void btn_PDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PDActionPerformed
        PanDulce pd = new PanDulce();
        pd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_PDActionPerformed

//Botón Conteo Pan
    private void btn_CPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CPActionPerformed
        ConteoPanHorneado cph = new ConteoPanHorneado();
        cph.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CPActionPerformed

//Botón Inventario
    private void btn_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IActionPerformed
        MenuInventario inventario = new MenuInventario();
        inventario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_IActionPerformed

//Botón Cliente Reparto
    private void btn_CRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CRActionPerformed
        ClienteReparto cliente = new ClienteReparto();
        cliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CRActionPerformed

//Botón Reporte Ventas
    private void btn_RVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RVActionPerformed
        ReportesVenta reportes = new ReportesVenta();
        reportes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEncargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenCP;
    private javax.swing.JLabel ImagenCR;
    private javax.swing.JLabel ImagenI;
    private javax.swing.JLabel ImagenPB;
    private javax.swing.JLabel ImagenPD;
    private javax.swing.JLabel ImagenRV;
    private javax.swing.JPanel PanelAbajo;
    private javax.swing.JPanel PanelArriba;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel Panel_CP;
    private javax.swing.JPanel Panel_CR;
    private javax.swing.JPanel Panel_I;
    private javax.swing.JPanel Panel_PB;
    private javax.swing.JPanel Panel_PD;
    private javax.swing.JPanel Panel_RV;
    private javax.swing.JButton btnCSME;
    private javax.swing.JButton btn_CP;
    private javax.swing.JButton btn_CR;
    private javax.swing.JButton btn_I;
    private javax.swing.JButton btn_PB;
    private javax.swing.JButton btn_PD;
    private javax.swing.JButton btn_RV;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblCR;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblLeyenda;
    private javax.swing.JLabel lblPB;
    private javax.swing.JLabel lblPD;
    private javax.swing.JLabel lblRV;
    // End of variables declaration//GEN-END:variables
}
