/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

import ClasesPlanas.LoginUsuarios;
import ConexionBD.Conexion;
import static ConexionBD.Conexion.con;
import java.sql.Connection;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Paola Barrera Tenorio 2192007348
 */
public class Perdidas extends javax.swing.JFrame {

    /**
     * Creates new form Perdidas
     */
    public Perdidas() {
        initComponents();
        
        this.setTitle("Panificadora La Izcalli");
        this.setLocationRelativeTo(Perdidas.this);
        this.setResizable(false);
        
        Fecha();
        Mostrar("Perdidas");
        llenarComboBox(cmbCajera, (Connection) con);
        TxtFields();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPerdidas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLeyenda = new javax.swing.JLabel();
        btnRegresarPerdidas = new javax.swing.JButton();
        btnGuardarPerdidas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPanBlanco = new javax.swing.JLabel();
        lblPiezasPB = new javax.swing.JLabel();
        txtPiezasPBPerdidas = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPanDulce = new javax.swing.JLabel();
        lblPiezasPD = new javax.swing.JLabel();
        txtPiezasPDPerdidas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPerdidas = new javax.swing.JTable();
        lblFechaDia = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbCajera = new javax.swing.JComboBox<>();
        jCalendar2 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 214, 155));
        jPanel1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(165, 105, 66));

        lblPerdidas.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        lblPerdidas.setForeground(new java.awt.Color(255, 255, 255));
        lblPerdidas.setText("- Perdidas -");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(lblPerdidas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblPerdidas)
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(165, 105, 66));

        lblLeyenda.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        lblLeyenda.setForeground(new java.awt.Color(255, 255, 255));
        lblLeyenda.setText("\"La Izcalli \"");

        btnRegresarPerdidas.setBackground(new java.awt.Color(255, 214, 155));
        btnRegresarPerdidas.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnRegresarPerdidas.setText("Regresar");
        btnRegresarPerdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPerdidasActionPerformed(evt);
            }
        });

        btnGuardarPerdidas.setBackground(new java.awt.Color(255, 214, 155));
        btnGuardarPerdidas.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnGuardarPerdidas.setText("Guardar");
        btnGuardarPerdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPerdidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRegresarPerdidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarPerdidas)
                        .addGap(160, 160, 160))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarPerdidas)
                    .addComponent(btnGuardarPerdidas))
                .addGap(18, 18, 18)
                .addComponent(lblLeyenda)
                .addGap(36, 36, 36))
        );

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel2.setText("Una vez finalizado el día laboral, llene los siguientes campos con las mermas sobrantes");

        jSeparator1.setBackground(new java.awt.Color(165, 105, 66));
        jSeparator1.setForeground(new java.awt.Color(165, 105, 66));

        lblPanBlanco.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPanBlanco.setText("- PAN BLANCO -");

        lblPiezasPB.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblPiezasPB.setText("Piezas de pan blanco sobrante");

        txtPiezasPBPerdidas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(165, 105, 66));
        jSeparator2.setForeground(new java.awt.Color(165, 105, 66));

        lblPanDulce.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblPanDulce.setText("- PAN DULCE -");

        lblPiezasPD.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblPiezasPD.setText("Piezas de pan dulce sobrante");

        txtPiezasPDPerdidas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        TablaPerdidas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        TablaPerdidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaPerdidas);

        lblFechaDia.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblFechaDia.setText("Fecha");

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel1.setText("Seleccionar a la cajera que registra las pérdidas");

        cmbCajera.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        cmbCajera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCalendar2.setPreferredSize(new java.awt.Dimension(200, 160));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPanBlanco)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPanDulce)
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblPiezasPB)
                        .addGap(49, 49, 49)
                        .addComponent(txtPiezasPBPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(lblFechaDia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(164, 164, 164))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(lblPiezasPD)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCajera, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPiezasPDPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDia)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPanBlanco)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPiezasPBPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPiezasPB))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPanDulce)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPiezasPDPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPiezasPD))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCajera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Botón Regresar
    private void btnRegresarPerdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPerdidasActionPerformed
        MenuCajera cajera = new MenuCajera();
        cajera.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarPerdidasActionPerformed

//Botón Guardar
    private void btnGuardarPerdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPerdidasActionPerformed
        Agregar();
    }//GEN-LAST:event_btnGuardarPerdidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perdidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perdidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perdidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perdidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perdidas().setVisible(true);
            }
        });
    }
//------------------------------------------------------------------------------    
    //Método para mostrar en la tabla los datos de MySQL
//------------------------------------------------------------------------------
    public void Mostrar(String tabla) {
    String sql = "SELECT * FROM " + tabla;
    Conexion con = new Conexion();
    java.sql.Connection conexion = con.conectar();

    DefaultTableModel model = new DefaultTableModel();
    String[] columnas = {"ID", "Fecha", "Piezas Pan Blanco", "Piezas Pan Dulce", "Usuario"};
    
    
    for (String columna : columnas) {
        model.addColumn(columna);
    }

    TablaPerdidas.setModel(model);

    try (java.sql.Statement st = conexion.createStatement(); ResultSet rs = st.executeQuery(sql)) {
        while (rs.next()) {
            String[] datos = new String[columnas.length];
            for (int i = 0; i < columnas.length; i++) {
                datos[i] = rs.getString(i + 1);
            }
          
            model.addRow(datos);
        }
        
        // Modificar el ancho de las columnas
        TableColumnModel modeloColumnas = TablaPerdidas.getColumnModel();
        modeloColumnas.getColumn(0).setPreferredWidth(1);  // ID
        modeloColumnas.getColumn(1).setPreferredWidth(30); // Fecha
        modeloColumnas.getColumn(2).setPreferredWidth(15);// Piezas Pan Blanco
        modeloColumnas.getColumn(3).setPreferredWidth(15); // Piezas Pan Dulce
        modeloColumnas.getColumn(4).setPreferredWidth(1); // Usuario
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error en executeQuery: " + e.getMessage());
    } finally {
        try {
            if (conexion != null && !conexion.isClosed()) {
                conexion.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + ex.getMessage());
        }
    }
}    
//------------------------------------------------------------------------------

    
//------------------------------------------------------------------------------
    //Método para limitar a escribir solo números en los Textfield
//------------------------------------------------------------------------------
    private void limitarNumeros(JTextField textField) {
        textField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) { // Solo permite números
                    e.consume(); // Bloquea la entrada si no es un número
                }
            }
        });
    }
//------------------------------------------------------------------------------

    
//------------------------------------------------------------------------------
    //Método para txtFields
//------------------------------------------------------------------------------
    private void TxtFields(){
    
    limitarNumeros(txtPiezasPBPerdidas);
    limitarNumeros(txtPiezasPDPerdidas);
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para generar la fecha 
//------------------------------------------------------------------------------
    private void Fecha(){

    LocalDate hoy = LocalDate.now();
    DateTimeFormatter formatoDia = DateTimeFormatter.ofPattern("EEEE", new Locale("es", "ES"));
    lblFechaDia.setText("Fecha: " + hoy.format(formatoDia));
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaActual = sdf.format(new Date());
    lblFecha.setText( fechaActual);
}    
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para agregar los datos de los TxtFields a la tabla ReportesVenta
//------------------------------------------------------------------------------
    private void Agregar() {                                            
                                           
    Date fechaRV = parseDate(lblFecha.getText()); 
    int piezasPB = Integer.parseInt(txtPiezasPBPerdidas.getText());
    int piezasPD = Integer.parseInt(txtPiezasPDPerdidas.getText());
    String seleccionado = cmbCajera.getSelectedItem().toString();
    String idString = seleccionado.split(" - ")[0]; // Tomamos solo el ID antes del guión
    int idUsuario = Integer.parseInt(idString);
    
    if (fechaRV == null) {
        JOptionPane.showMessageDialog(null, "Fecha inválida. Ingrese en formato yyyy-MM-dd.");
        return; // Sale del método si la fecha es inválida
    }
    
    java.sql.Date fechaSQL = new java.sql.Date(fechaRV.getTime()); 

    try {
        java.sql.Connection con =  Conexion.conectar(); 
        PreparedStatement ps = con.prepareStatement("INSERT INTO perdidas (P_Fecha, P_PiezasPanBlanco, P_PiezasPanDulce, P_IDUsuario) VALUES (?,?,?,?)");

        ps.setDate(1, fechaSQL);
        ps.setInt(2, piezasPB); 
        ps.setInt(3, piezasPD); 
        ps.setInt(4, idUsuario);

        
       
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registro guardado");
        
        //Actualizar la tabla para que aparezca el registro nuevo
        Mostrar("perdidas");
        
        con.close(); // Cierra la conexión

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage());
    }
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para llenar el comboBox
//------------------------------------------------------------------------------
    public void llenarComboBox(JComboBox<String> comboBox, Connection conn) {
    String sql = "SELECT idUsuario, U_nombre FROM usuario WHERE U_Rol = 'cajera'"; 
    java.sql.Connection con = Conexion.conectar();
     
    try (PreparedStatement stmt = con.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        comboBox.removeAllItems(); // Limpiar el JComboBox antes de llenarlo

        while (rs.next()) {
            int idUsuario = rs.getInt("idUsuario");
            String nombre = rs.getString("U_nombre");
            comboBox.addItem(idUsuario + " - " + nombre); // Ej: "3 - Ana Torres"
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos en el ComboBox.");
    }
}
//------------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPerdidas;
    private javax.swing.JButton btnGuardarPerdidas;
    private javax.swing.JButton btnRegresarPerdidas;
    private javax.swing.JComboBox<String> cmbCajera;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaDia;
    private javax.swing.JLabel lblLeyenda;
    private javax.swing.JLabel lblPanBlanco;
    private javax.swing.JLabel lblPanDulce;
    private javax.swing.JLabel lblPerdidas;
    private javax.swing.JLabel lblPiezasPB;
    private javax.swing.JLabel lblPiezasPD;
    private javax.swing.JTextField txtPiezasPBPerdidas;
    private javax.swing.JTextField txtPiezasPDPerdidas;
    // End of variables declaration//GEN-END:variables

private int ParseInt(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Date parseDate(String fecha) {
         try {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd"); 
        java.util.Date fechaUtil = formato.parse(fecha);
        return new java.sql.Date(fechaUtil.getTime());
    } 
         catch (ParseException e) {
        System.out.println("Error al convertir la fecha: " + e.getMessage());
        return null; // Devuelve null si hay error
    }
    }
}

