/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

import ConexionBD.Conexion;
import static ConexionBD.Conexion.con;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Paola Barrera Tenorio 2192007348
 */

public class ReportesVenta extends javax.swing.JFrame {

    /**
     * Creates new form ReportesVenta
     */
    public ReportesVenta() {
        initComponents();
        
        this.setTitle("Panificadora La Izcalli");
        this.setLocationRelativeTo(ReportesVenta.this);
        this.setResizable(false);
            
        Fecha();
        TxtFields();
        Mostrar("listapedido");
        llenarComboBox(cmbUsuario, (Connection) con);
        SumaImporteTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblReportesVenta = new javax.swing.JLabel();
        lblFechaDia = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblVentaRepartos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReportesVenta = new javax.swing.JTable();
        lblTotalRepartos = new javax.swing.JLabel();
        txtTotalRepartos = new javax.swing.JTextField();
        lblTotalVentasRegistradas = new javax.swing.JLabel();
        txtTotalVentasRegistradas = new javax.swing.JTextField();
        lblTotalVenta = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        txtGastos = new javax.swing.JTextField();
        lblPrestamoMonedas = new javax.swing.JLabel();
        txtPrestamoMonedas = new javax.swing.JTextField();
        lblPrestamoBilletes = new javax.swing.JLabel();
        txtPrestamoBilletes = new javax.swing.JTextField();
        lblDineroCaja = new javax.swing.JLabel();
        txtDineroCaja = new javax.swing.JTextField();
        lblTotalCaja = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCajaRegistradora = new javax.swing.JLabel();
        lblInformacionCajera = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        btnSumaTotalVenta = new javax.swing.JButton();
        btnSumaTotalCaja = new javax.swing.JButton();
        cmbUsuario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblTotalV = new javax.swing.JLabel();
        lblTotalC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1022, 1200));

        jPanel1.setBackground(new java.awt.Color(255, 214, 155));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 1027));

        jPanel2.setBackground(new java.awt.Color(165, 105, 66));

        lblReportesVenta.setFont(new java.awt.Font("STLiti", 0, 48)); // NOI18N
        lblReportesVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblReportesVenta.setText("- Reportes de venta -");

        lblFechaDia.setBackground(new java.awt.Color(0, 0, 0));
        lblFechaDia.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        lblFechaDia.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaDia.setText("Fecha");

        lblFecha.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReportesVenta)
                .addGap(92, 92, 92)
                .addComponent(lblFechaDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(184, 184, 184))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblReportesVenta)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaDia)
                            .addComponent(lblFecha))
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(165, 105, 66));

        jLabel2.setFont(new java.awt.Font("STLiti", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("\" La izcalli\" ");

        btnRegresar.setBackground(new java.awt.Color(252, 211, 125));
        btnRegresar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(252, 211, 125));
        btnGuardar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(99, 99, 99)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(184, 184, 184))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar)
                            .addComponent(btnGuardar))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblVentaRepartos.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblVentaRepartos.setText("Ventas a repartos");

        jSeparator1.setBackground(new java.awt.Color(165, 105, 66));
        jSeparator1.setForeground(new java.awt.Color(165, 105, 66));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        TablaReportesVenta.setBackground(new java.awt.Color(255, 255, 204));
        TablaReportesVenta.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        TablaReportesVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Nombre Cliente de Reparto", "Total a pagar"
            }
        ));
        jScrollPane1.setViewportView(TablaReportesVenta);

        lblTotalRepartos.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblTotalRepartos.setText("Total de repartos");

        txtTotalRepartos.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        txtTotalRepartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalRepartosActionPerformed(evt);
            }
        });

        lblTotalVentasRegistradas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblTotalVentasRegistradas.setText("Total ventas registradas");

        txtTotalVentasRegistradas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        lblTotalVenta.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblTotalVenta.setText("TOTAL VENTA");

        lblGastos.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblGastos.setText("Gastos realizados");

        txtGastos.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        lblPrestamoMonedas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblPrestamoMonedas.setText("Préstamo en monedas");

        txtPrestamoMonedas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        lblPrestamoBilletes.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblPrestamoBilletes.setText("Préstamo en billetes");

        txtPrestamoBilletes.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        lblDineroCaja.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        lblDineroCaja.setText("Dinero en efectivo total en caja");

        txtDineroCaja.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N

        lblTotalCaja.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lblTotalCaja.setText("TOTAL EN CAJA");

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel11.setText("***** EL TOTAL VENTA tiene que ser igual a al TOTAL EN CAJA *****");

        lblCajaRegistradora.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblCajaRegistradora.setText(" Caja registradora ");

        lblInformacionCajera.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblInformacionCajera.setText("Información de la cajera");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel3.setText("Al realizar el corte de caja, llene los siguientes campos con la información especifica para cada uno");

        jCalendar2.setMinimumSize(new java.awt.Dimension(200, 200));

        btnSumaTotalVenta.setBackground(new java.awt.Color(165, 105, 66));
        btnSumaTotalVenta.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnSumaTotalVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnSumaTotalVenta.setText("Realizar suma");
        btnSumaTotalVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaTotalVentaActionPerformed(evt);
            }
        });

        btnSumaTotalCaja.setBackground(new java.awt.Color(165, 105, 66));
        btnSumaTotalCaja.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnSumaTotalCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnSumaTotalCaja.setText("Realizar suma");
        btnSumaTotalCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaTotalCajaActionPerformed(evt);
            }
        });

        cmbUsuario.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        cmbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel1.setText("Cajera a cargo del corte de caja");

        lblTotalV.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblTotalV.setText("0.0");

        lblTotalC.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lblTotalC.setText("0.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCajaRegistradora)
                                        .addGap(161, 161, 161))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(lblTotalRepartos)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtTotalRepartos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTotalVentasRegistradas)
                                            .addComponent(lblTotalVenta))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTotalVentasRegistradas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(lblTotalV))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(btnSumaTotalVenta)))
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblTotalCaja)
                                        .addGap(40, 40, 40)
                                        .addComponent(lblTotalC))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(lblInformacionCajera))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPrestamoBilletes)
                                        .addComponent(lblPrestamoMonedas))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(lblDineroCaja))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(92, 92, 92)
                                                .addComponent(lblGastos)))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrestamoBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDineroCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrestamoMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(198, 198, 198)
                                        .addComponent(btnSumaTotalCaja))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(lblVentaRepartos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(lblInformacionCajera)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGastos)
                            .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrestamoMonedas)
                            .addComponent(txtPrestamoMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrestamoBilletes)
                            .addComponent(txtPrestamoBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDineroCaja)
                            .addComponent(txtDineroCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(btnSumaTotalCaja))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblVentaRepartos)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalRepartos)
                            .addComponent(txtTotalRepartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(lblCajaRegistradora)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalVentasRegistradas)
                            .addComponent(txtTotalVentasRegistradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSumaTotalVenta))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotalVenta)
                        .addComponent(lblTotalV))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotalCaja)
                        .addComponent(lblTotalC)))
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalRepartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalRepartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalRepartosActionPerformed

//Botón Guardar
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Agregar();
        EstatusCorteCaja();
    }//GEN-LAST:event_btnGuardarActionPerformed

//Botón Regresar
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuEncargado encargado = new MenuEncargado();
        encargado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

//Botón Suma Total Venta
    private void btnSumaTotalVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaTotalVentaActionPerformed
      SumaTotalVenta();
    }//GEN-LAST:event_btnSumaTotalVentaActionPerformed

//Botón Suma Total Caja
    private void btnSumaTotalCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaTotalCajaActionPerformed
        SumaTotalCaja();
    }//GEN-LAST:event_btnSumaTotalCajaActionPerformed

    
    
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesVenta().setVisible(true);
            }
        });
    }
    
   
//------------------------------------------------------------------------------
    //Método para generar la fecha 
//------------------------------------------------------------------------------
private void Fecha(){

    LocalDate hoy = LocalDate.now();
    DateTimeFormatter formatoDia = DateTimeFormatter.ofPattern("EEEE", new Locale("es", "ES"));
    lblFechaDia.setText("Fecha: " + hoy.format(formatoDia));
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaActual = sdf.format(new Date());
    lblFecha.setText( fechaActual);
}    
//------------------------------------------------------------------------------    
    
    
//------------------------------------------------------------------------------
    //Llenado de la tabla con la información de MYSQL
//------------------------------------------------------------------------------
    public void Mostrar(String tabla) {
    
    String sql = "SELECT lp.idListaPedido, lp.LP_Fecha, cr.CR_Nombre, lp.LP_ImporteTotal " +
                 "FROM ListaPedido lp " +
                 "INNER JOIN ClienteReparto cr ON lp.LP_IDClienteReparto = cr.idClienteReparto " +
                 "WHERE DATE(lp.LP_Fecha) = CURDATE()";

    Conexion con = new Conexion();
    java.sql.Connection conexion = con.conectar();

    DefaultTableModel model = new DefaultTableModel();
    String[] columnas = {"ID", "Fecha", "Nombre Cliente Reparto", "Total a pagar"};
    
    for (String columna : columnas) {
        model.addColumn(columna);
    }

    TablaReportesVenta.setModel(model);

    try (java.sql.Statement st = conexion.createStatement(); ResultSet rs = st.executeQuery(sql)) {
        while (rs.next()) {
            String[] datos = new String[columnas.length];
            datos[0] = rs.getString("idListaPedido");
            datos[1] = rs.getString("LP_Fecha");
            datos[2] = rs.getString("CR_Nombre");
            datos[3] = rs.getString("LP_ImporteTotal");
            model.addRow(datos);
        }

        // Ajustar ancho de columnas
        TableColumnModel modeloColumnas = TablaReportesVenta.getColumnModel();
        modeloColumnas.getColumn(0).setPreferredWidth(1);   // ID
        modeloColumnas.getColumn(1).setPreferredWidth(30);  // Fecha
        modeloColumnas.getColumn(2).setPreferredWidth(100); // Nombre Cliente
        modeloColumnas.getColumn(3).setPreferredWidth(30);  // Total a Pagar

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error en executeQuery: " + e.getMessage());
    } finally {
        try {
            if (conexion != null && !conexion.isClosed()) {
                conexion.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + ex.getMessage());
        }
    }
}
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para limitar a escribir solo números en los Textfield
//------------------------------------------------------------------------------
    private void limitarNumeros(JTextField textField) {
    textField.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c = e.getKeyChar();
            
            // Si no es un dígito ni un punto
            if (!Character.isDigit(c) && c != '.') {
                e.consume(); // Bloquea
            }

            // Si ya hay un punto y se quiere escribir otro
            if (c == '.' && textField.getText().contains(".")) {
                e.consume(); // Bloquea el segundo punto
            }
        }
    });
}
//------------------------------------------------------------------------------  

    
//------------------------------------------------------------------------------
    //Método para txtFields
//------------------------------------------------------------------------------
    private void TxtFields(){
    
    limitarNumeros(txtDineroCaja);
    limitarNumeros(txtGastos);
    limitarNumeros(txtPrestamoBilletes);
    limitarNumeros(txtPrestamoMonedas);
    limitarNumeros(txtTotalVentasRegistradas);
    limitarNumeros(txtTotalRepartos);
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para realizar la sumatoria de los txtFields
//------------------------------------------------------------------------------
    private void SumaTotalVenta (){
    
    try {
        double repartos = Double.parseDouble(txtTotalRepartos.getText());
        double ventasRegistradas = Double.parseDouble(txtTotalVentasRegistradas.getText());

        double resultadoTotalVenta = repartos + ventasRegistradas;
        lblTotalV.setText(String.valueOf(resultadoTotalVenta));
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa solo números válidos", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para realizar la sumatoria de los txtFields
//------------------------------------------------------------------------------
    private void SumaTotalCaja (){
    
    try {
        double gastos = Double.parseDouble(txtGastos.getText());
        double monedas = Double.parseDouble(txtPrestamoMonedas.getText());
        double billetes = Double.parseDouble(txtPrestamoBilletes.getText());
        double efectivo = Double.parseDouble(txtDineroCaja.getText());

        double resultadoTotalCaja = gastos + monedas + billetes + efectivo;
        lblTotalC.setText(String.valueOf(resultadoTotalCaja));
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa solo números válidos", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para sumar la columna de ImporteTotal de la tabla ListaPedido
//------------------------------------------------------------------------------

    public void SumaImporteTotal() {
    String sql = "SELECT SUM(LP_ImporteTotal) AS Total " +
                 "FROM ListaPedido " +
                 "WHERE DATE(LP_Fecha) = CURDATE()";

    Conexion con = new Conexion();
    java.sql.Connection conexion = con.conectar();

    try (PreparedStatement pst = conexion.prepareStatement(sql)) {
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            double total = rs.getDouble("Total");
            txtTotalRepartos.setText(String.valueOf(total));
        } else {
            txtTotalRepartos.setText("0.0");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al calcular el total del día: " + e.getMessage());
    } finally {
        try {
            if (conexion != null && !conexion.isClosed()) {
                conexion.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + ex.getMessage());
        }
    }
}
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para agregar los datos de los TxtFields a la tabla ReportesVenta
//------------------------------------------------------------------------------
    private void Agregar() {                                            
                                           
    Date fechaRV = parseDate(lblFecha.getText()); 
    float totalRepartos = Float.parseFloat(txtTotalRepartos.getText());
    float ventasRegistradas = Float.parseFloat(txtTotalVentasRegistradas.getText());
    float totalVenta = Float.parseFloat(lblTotalV.getText());
    float gastos = Float.parseFloat(txtGastos.getText());
    float monedas = Float.parseFloat(txtPrestamoMonedas.getText());
    int billetes = Integer.parseInt(txtPrestamoBilletes.getText());
    float dineroCaja = Float.parseFloat(txtDineroCaja.getText());
    float totalCaja = Float.parseFloat(lblTotalC.getText());
     
    String seleccionado = cmbUsuario.getSelectedItem().toString();
    String idString = seleccionado.split(" - ")[0]; // Tomamos solo el ID antes del guión
    int idUsuario = Integer.parseInt(idString);
    
    if (fechaRV == null) {
        JOptionPane.showMessageDialog(null, "Fecha inválida. Ingrese en formato yyyy-MM-dd.");
        return; // Sale del método si la fecha es inválida
    }
    
    java.sql.Date fechaSQL = new java.sql.Date(fechaRV.getTime()); 

    try {
        java.sql.Connection con =  Conexion.conectar(); 
        PreparedStatement ps = con.prepareStatement("INSERT INTO reporteventas (RV_Fecha, RV_Gastos, RV_PrestamoMonedas, RV_PrestamoBilletes, RV_DineroCaja, RV_TotalCaja, RV_VentasRegistradas, RV_VentasRepartos, RV_TotalVenta, RV_IDUsuario) VALUES (?,?,?,?,?,?,?,?,?,?)");

        ps.setDate(1, fechaSQL);
        ps.setFloat(2, gastos); 
        ps.setFloat(3, monedas); 
        ps.setInt(4, billetes); 
        ps.setFloat(5, dineroCaja);
        ps.setFloat(6, totalCaja);
        ps.setFloat(7, ventasRegistradas);
        ps.setFloat(8, totalRepartos);
        ps.setFloat(9, totalVenta);
        ps.setInt(10, idUsuario);
        

        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registro guardado");
        
        //Actualizar la tabla para que aparezca el registro nuevo
        Mostrar("reporteventas");
        
        
        con.close(); // Cierra la conexión

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage());
    }
    }
//------------------------------------------------------------------------------
    
    
//------------------------------------------------------------------------------
    //Método para limpiar los campos
//------------------------------------------------------------------------------    
private void LimpiarCampos(){

        txtDineroCaja.setText("");
        txtGastos.setText("");
        txtPrestamoBilletes.setText("");
        txtPrestamoMonedas.setText("");
        txtTotalRepartos.setText("");
        txtTotalVentasRegistradas.setText("");

}
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
    //Método para llenar el comboBox
//------------------------------------------------------------------------------
 
public void llenarComboBox(JComboBox<String> comboBox, Connection conn) {
    String sql = "SELECT idUsuario, U_nombre FROM usuario WHERE U_Rol = 'cajera'"; 
    java.sql.Connection con = Conexion.conectar();
     
    try (PreparedStatement stmt = con.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        comboBox.removeAllItems(); // Limpiar el JComboBox antes de llenarlo

        while (rs.next()) {
            int idUsuario = rs.getInt("idUsuario");
            String nombre = rs.getString("U_nombre");
            comboBox.addItem(idUsuario + " - " + nombre); // Ej: "3 - Ana Torres"
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos en el ComboBox.");
    }
}
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
    //Método para hacer la comparación del TotalVenta y TotalCaja
//------------------------------------------------------------------------------

    private void EstatusCorteCaja(){
    
     float cantidad1 = Float.parseFloat(lblTotalV.getText());
    float cantidad2 = Float.parseFloat(lblTotalC.getText());
    
    if (cantidad1 == cantidad2) {
        JOptionPane.showMessageDialog(null, "El corte de caja ha sido exitoso");
    } else if (cantidad1 > cantidad2) {
        float falta = cantidad1 - cantidad2;
        JOptionPane.showMessageDialog(null, "Hace falta $" + falta + " de dinero");
    } else { // cantidad1 < cantidad2
        float sobra = cantidad2 - cantidad1;
        JOptionPane.showMessageDialog(null, "Sobra $" + sobra + " de dinero");
    }
   
    LimpiarCampos();
    }

//------------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaReportesVenta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSumaTotalCaja;
    private javax.swing.JButton btnSumaTotalVenta;
    private javax.swing.JComboBox<String> cmbUsuario;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCajaRegistradora;
    private javax.swing.JLabel lblDineroCaja;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaDia;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblInformacionCajera;
    private javax.swing.JLabel lblPrestamoBilletes;
    private javax.swing.JLabel lblPrestamoMonedas;
    private javax.swing.JLabel lblReportesVenta;
    private javax.swing.JLabel lblTotalC;
    private javax.swing.JLabel lblTotalCaja;
    private javax.swing.JLabel lblTotalRepartos;
    private javax.swing.JLabel lblTotalV;
    private javax.swing.JLabel lblTotalVenta;
    private javax.swing.JLabel lblTotalVentasRegistradas;
    private javax.swing.JLabel lblVentaRepartos;
    private javax.swing.JTextField txtDineroCaja;
    private javax.swing.JTextField txtGastos;
    private javax.swing.JTextField txtPrestamoBilletes;
    private javax.swing.JTextField txtPrestamoMonedas;
    private javax.swing.JTextField txtTotalRepartos;
    private javax.swing.JTextField txtTotalVentasRegistradas;
    // End of variables declaration//GEN-END:variables

    private int ParseInt(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Date parseDate(String fecha) {
         try {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd"); 
        java.util.Date fechaUtil = formato.parse(fecha);
        return new java.sql.Date(fechaUtil.getTime());
    } 
         catch (ParseException e) {
        System.out.println("Error al convertir la fecha: " + e.getMessage());
        return null; // Devuelve null si hay error
    }
    }
}

